.TH GIT\-ISTASH 1 "2025-12-15" "git\-istash 1.6.0"
.nh
.ad l


.SH NAME
git\-istash \- Handle Git stashes without arbitrary limitations of the original command


.SH SYNOPSIS
.nf
\fBgit istash\fR [<options>] [<subcommand>] (\-h\~|\~\-\-help\~|\~\-\-man\~|
            |\~\-V\~|\~\-\-version)
\fBgit istash\fR [<options>] (create\~|\~snatch\~|\~save\~|\~push) [\-a\~|\~\-\-all]
            [\-\-allow\-empty] [\-k\~|\~\-\-[no\-]keep\-index]
            [\-l\~|\~\-\-leave\-staged] [(\-m\~|\~\-\-message)\~<\fImessage\fR>] [\-\-patch]
            [\-\-patchspec\-file\-nul] [\-\-patchspec\-from\-file=<\fIfile\fR>]
            [\-S\~|\~\-\-staged] [\-u\~|\~\-\-[no\-]include\-untracked]
            [\-\-] [<\fIpathspec\fR>...]
\fBgit istash\fR [<options>] [\-a\~|\~\-\-all] [\-\-allow\-empty]
            [\-k\~|\~\-\-[no\-]keep\-index] [\-l\~|\~\-\-leave\-staged]
            [(\-m\~|\~\-\-message)\~<\fImessage\fR>] [\-\-patch] [\-\-patchspec\-file\-nul]
            [\-\-patchspec\-from\-file=<\fIfile\fR>] [\-S\~|\~\-\-staged]
            [\-u\~|\~\-\-[no\-]include\-untracked] [\-\-\~<\fIpathspec\fR>...]
\fBgit istash\fR [<options>] (pop\~|\~apply) [\-\-summary\~<mode>] [<\fIstash\fR>]
\fBgit istash\fR [<options>] [pop\~|\~apply] (\-c\~|\~\-\-continue) [\-\-summary\~<mode>]
\fBgit istash\fR [<options>] [pop\~|\~apply] (\-\-abort\~|\~\-\-quit)
\fBgit istash\fR [<options>] (c\~|\~continue) [\-\-summary\~<mode>]
\fBgit istash\fR [<options>] (abort\~|\~quit)
.fi


.SH DESCRIPTION
\fBgit istash\fR ("improved stash") is an alternative implementation for \fBgit stash\fR, mostly compatible with stash entries created by it (other than special cases in \fBgit stash\fR which are not present in \fBgit istash\fR). \
Use \fBgit istash\fR subcommands as a replacement for \fBgit stash\fR subcommands with the same names.
.sp

\fBgit istash create\fR, \fBgit istash snatch\fR, \fBgit istash save\fR and \fBgit istash push\fR:
.RS 4
All of these subcommands create a new stash entry containing chosen files (specified by options and pathspecs). \
They differ in whether they store the created stash and whether they delete the stashed changed from the working directory.
.TS
box;
c | c | c
r | l | l.
Subcommand	Keeps the changes in WD	Stores the created stash
=
\fBcreate\fR	YES	NO
\fBsnatch\fR	NO (can keep index)	NO
\fBsave\fR	YES	YES
\fBpush\fR	NO (can keep index)	YES
.TE
(\fBgit istash create\fR and \fBgit istash push\fR are very close equivalents of their vanilla counterparts, except for some corner cases and support for various options. \
\fBgit istash snatch\fR and \fBgit istash save\fR have no vanilla equivalents - they are somewhere half way between \fBcreate\fR and \fBpush\fR.)
.RE

\fBgit istash apply\fR and \fBgit istash pop\fR:
.RS 4
Both of these subcommands restore stashed changes to the working directory. \
Additionally, \fBgit istash pop\fR removes the stash entry on success. \
(For this reason \fBpop\fR cannot be used for a stash that is not in the stash ref, while \fBapply\fR can be.)
.br
When there are no conflicts, these work the same as \fBgit stash apply \-\-index\fR and \fBgit stash pop \-\-index\fR.
.TS
box;
c | c
r | l.
Subcommand	Removes the stash from the stash ref
=
\fBapply\fR	NO
\fBpop\fR	YES (if it succeeded)
.TE
In case of conflicts, instead of refusing and demanding to run it without \fB\-\-index\fR, they temporarily apply index and working directory changes as separate commits, stopping to resolve conflicts whenever it's necessary (similarly to \fBgit rebase\fR). \
After the conflicts are resolved, the subcommands can be resumed with \fB\-\-continue\fR. \
Alternatively, \fB\-\-abort\fR can be used to cancel the operation and return to the repository state before it started, or \fB\-\-quit\fR to cancel the operation without restoring anything.
.br
Because of the multi-stage conflict resolution, \fIthe index saved to the stash entry will be preserved\fR (unlike in \fBgit stash\fR equivalent subcommands).
.br
Additionally, the state of working copy, from before the \fBapply\fR / \fBpop\fR has started, is backed up as a separate stash entry (which is not stored anywhere but it can be found in the command's output if needed).
.br
After the operation is complete, it prints a summary of all changes done to the working directory. \
This includes \fIonly\fR the changes related to the stash and not the changes that were already there before running the command, which is different from vanilla stash which just runs \fBgit status\fR. \
(See also \fB--summary\fR.)
.RE

\fBgit istash c\fR, \fBgit istash create\fR, \fBgit istash abort\fR and \fBgit istash quit\fR
.RS 4
Those are aliases for options with the same name. (Just a syntax sugar.)
.br
See \fB\-c\fR, \fB\-\-continue\fR, \fB\-\-abort\fR and \fB\-\-quit\fR.
.RE


.SH SUBCOMMANDS

.PP
\fBcreate\fR [\-a\~|\~\-\-all] [\-\-allow\-empty] [\-l\~|\~\-\-leave\-staged] [(\-m\~|\~\-\-message)\~<\fImessage\fR>] [\-\-patch] [\-\-patchspec\-file\-nul] [\-\-patchspec\-from\-file=<\fIfile\fR>] [\-S\~|\~\-\-staged] [\-u\~|\~\-\-[no\-]include\-untracked] [\-\-] [<\fIpathspec\fR>...]
.RS 4
Like \fBgit stash create\fR, except some minor differences and support for options.
.br
Every sensible combination of options is supported (including \fB\-\-all\fR in conjunction with \fB\-\-no\-include\-untracked\fR which results in adding ignored files but leaving non-ignored untracked ones). \
The option \fB\-\-patch\fR works also with untracked files. \
Failing to create a stash is much more reliable especially in the case when there is no files to stash. \
(There is a new option \fB\-\-allow\-empty\fR to bypass that.) \
Stashes can be created on orphan branches. \
The pathspec affects stashed index too. \
And finally, the options \fB\-\-patch\fR and \fB\-\-pathspec\-from\-file\fR are allowed together.
.RE

.PP
\fBsnatch\fR [\-a\~|\~\-\-all] [\-\-allow\-empty] [\-k\~|\~\-\-[no\-]keep\-index] [\-l\~|\~\-\-leave\-staged] [(\-m\~|\~\-\-message)\~<\fImessage\fR>] [\-\-patch] [\-\-patchspec\-file\-nul] [\-\-patchspec\-from\-file=<\fIfile\fR>] [\-S\~|\~\-\-staged] [\-u\~|\~\-\-[no\-]include\-untracked] [\-\-] [<\fIpathspec\fR>...]
.RS 4
Same as \fBgit istash push\fR, except the created stash \fIisn't stored\fR.
.br
Every sensible combination of options is supported (including \fB\-\-all\fR in conjunction with \fB\-\-no\-include\-untracked\fR which results in adding ignored files but leaving non-ignored untracked ones). \
The option \fB\-\-patch\fR works also with untracked files. \
Failing to create a stash is much more reliable especially in the case when there is no files to stash. \
(There is a new option \fB\-\-allow\-empty\fR to bypass that.) \
Stashes can be created on orphan branches. \
The pathspec affects stashed index too. \
And finally, the options \fB\-\-patch\fR and \fB\-\-pathspec\-from\-file\fR are allowed together.
.RE

.PP
\fBsave\fR [\-a\~|\~\-\-all] [\-\-allow\-empty] [\-l\~|\~\-\-leave\-staged] [(\-m\~|\~\-\-message)\~<\fImessage\fR>] [\-\-patch] [\-\-patchspec\-file\-nul] [\-\-patchspec\-from\-file=<\fIfile\fR>] [\-S\~|\~\-\-staged] [\-u\~|\~\-\-[no\-]include\-untracked] [\-\-] [<\fIpathspec\fR>...]
.RS 4
This \fIisn't\fR equivalent of \fBgit stash save\fR. \
It's similar to \fBgit istash create\fR, except that the created stash is stored.
.br
Every sensible combination of options is supported (including \fB\-\-all\fR in conjunction with \fB\-\-no\-include\-untracked\fR which results in adding ignored files but leaving non-ignored untracked ones). \
The option \fB\-\-patch\fR works also with untracked files. \
Failing to create a stash is much more reliable especially in the case when there is no files to stash. \
(There is a new option \fB\-\-allow\-empty\fR to bypass that.) \
Stashes can be created on orphan branches. \
The pathspec affects stashed index too. \
And finally, the options \fB\-\-patch\fR and \fB\-\-pathspec\-from\-file\fR are allowed together.
.RE

.PP
\fBpush\fR [\-a\~|\~\-\-all] [\-\-allow\-empty] [\-k\~|\~\-\-[no\-]keep\-index] [\-l\~|\~\-\-leave\-staged] [(\-m\~|\~\-\-message)\~<\fImessage\fR>] [\-\-patch] [\-\-patchspec\-file\-nul] [\-\-patchspec\-from\-file=<\fIfile\fR>] [\-S\~|\~\-\-staged] [\-u\~|\~\-\-[no\-]include\-untracked] [\-\-] [<\fIpathspec\fR>...]
.RS 4
Like \fBgit stash push\fR, except some minor differences.
.br
Every sensible combination of options is supported (including \fB\-\-all\fR in conjunction with \fB\-\-no\-include\-untracked\fR which results in adding ignored files but leaving non-ignored untracked ones). \
The option \fB\-\-patch\fR works also with untracked files. \
Failing to create a stash is much more reliable especially in the case when there is no files to stash. \
(There is a new option \fB\-\-allow\-empty\fR to bypass that.) \
Stashes can be created on orphan branches. \
The pathspec affects stashed index too. \
And finally, the options \fB\-\-patch\fR and \fB\-\-pathspec\-from\-file\fR are allowed together.
.RE

.PP
\fBapply\fR [<\fIstash\fR>\~|\~\-c\~|\~\-\-continue\~|\~\-\-abort\~|\~\-\-quit] [\-\-summary\~<mode>]
.RS 4
Like \fBgit stash apply \-\-index\fR, but it handles staged and unstaged conflicts separately, preventing those scopes from mixing. \
\fB<stash>\fR may be any commit that looks like a commit created by \fBgit stash push\fR or \fBgit stash create\fR.
.sp
This is the inverse operation of \fBgit istash snatch\fR.
.RE

.PP
\fBpop\fR [<\fIstash\fR>\~|\~\-c\~|\~\-\-continue\~|\~\-\-abort\~|\~\-\-quit] [\-\-summary\~<mode>]
.RS 4
Like \fBgit stash pop \-\-index\fR, but it handles staged and unstaged conflicts separately, preventing those scopes from mixing. \
Unlike \fBgit stash pop\fR, it can handle stashes referenced by name (\fBstash^{/<name>}\fR).
.sp
The only differences from \fBgit istash apply\fR are that \fBpop\fR cannot use an arbitrary commit as \fB<stash>\fR and it removes the stash entry on success. \
(Thus, the given stash has to be in stash ref or the command will refuse to run.) \
In case of conflicts, the stash is dropped only after all conflicts are successfully resolved.
.sp
This is the inverse operation of \fBgit istash push\fR.
.RE

.PP
\fBc\fR | \fBcontinue\fR [\-\-summary\~<mode>]
.RS 4
This is just a convenient alias for \fB\-c\fR / \fB\-\-continue\fR. \
(\fBgit istash continue\fR is the same as \fBgit istash \-\-continue\fR.)
.br
Other abbreviations (like \fBconti\fR) are also allowed.
.RE

.PP
\fBabort\fR
.RS 4
This is just a convenient alias for \fB\-\-abort\fR. \
(\fBgit istash abort\fR is the same as \fBgit istash \-\-abort\fR.)
.RE

.PP
\fBquit\fR
.RS 4
This is just a convenient alias for \fB\-\-quit\fR. \
(\fBgit istash quit\fR is the same as \fBgit istash \-\-quit\fR.)
.RE


.SH OPTIONS

.PP
\fB\-a\fR, \fB\-\-all\fR
.RS 4
This option is only valid for \fBcreate\fR, \fBsnatch\fR, \fBsave\fR and \fBpush\fR subcommands.
.sp
All ignored and untracked files are also stashed and then removed.
.RE

.PP
\fB\-\-allow\-empty\fR
.RS 4
This option is only valid for \fBcreate\fR, \fBsnatch\fR, \fBsave\fR and \fBpush\fR subcommands.
.sp
Stash is created even if there is no changes or options / pathspec exclude all of them. \
The exit code becomes 0 in such cases.
.RE

.PP
\fB\-k\fR, \fB\-\-keep\-index\fR, \fB\-\-no\-keep\-index\fR
.RS 4
This option is only valid for \fBsnatch\fR and \fBpush\fR subcommands, and also allowed for \fBcreate\fR and \fBsave\fR.
.sp
It behaves identically to the same option in the vanilla command. \
All changes already added to the index are left intact (but still stashed). \
See also \fB\-\-leave\-staged\fR.
.br
(For subcommands \fBcreate\fR and \fBsave\fR it has no effect unless \fB\-\-remove\-stashed\fR is also specified.)
.br
(\fB\-\-no\-keep\-index\fR not that useful; it exist mainly to comply with the standard stash command.)
.RE

.PP
\fB\-l\fR, \fB\-\-leave\-staged\fR
.RS 4
This option is only valid for \fBcreate\fR, \fBsnatch\fR, \fBsave\fR and \fBpush\fR subcommands.
.sp
All changes already added to the index are not stashed and left intact. \
(Unlike \fB\-\-keep\-index\fR which also adds the index to the stash.) \
See also \fB\-\-keep\-index\fR and \fB\-\-staged\fR.
.RE

.PP
\fB\-m\fR <\fImessage\fR>, \fB\-\-message\fR <\fImessage\fR>
.RS 4
This option is only valid for \fBcreate\fR, \fBsnatch\fR, \fBsave\fR and \fBpush\fR subcommands.
.sp
Custom message (name) for stash is used instead of the one generated using the last commit message.
.RE

.PP
\fB\-\-patch\fR
.RS 4
This option is only valid for \fBcreate\fR, \fBsnatch\fR, \fBsave\fR and \fBpush\fR subcommands.
.sp
Interactively select hunks from the diff between HEAD and the working tree to be stashed.
.br
The stash entry is constructed such that its index state is the same as the index state of your repository, and its worktree contains only the changes you selected interactively. \
The selected changes are then rolled back from your worktree. \
See the “Interactive Mode” section of \fBgit\-add\fR(1) to learn how to operate the \fB\-\-patch\fR mode.
.sp
Unlike in the standard \fBgit stash\fR command, the option \fB\-\-keep\-index\fR is \fInot\fR affected.
.RE

.PP
\fB\-\-pathspec\-from\-file\fR=<\fIfile\fR>
.RS 4
This option is only valid for \fBcreate\fR, \fBsnatch\fR, \fBsave\fR and \fBpush\fR subcommands.
.sp
Pathspec is passed in \fB<file>\fR instead of command line arguments. \
If \fB<file>\fR is exactly \fB\-\fR then standard input is used (so this is not allowed with \fB\-\-patch\fR). \
Pathspec elements are separated by LF or CR/LF and are interpreted the same way as the one passed via the command line. \
See also \fB\-\-pathspec\-file\-nul\fR.
.RE

.PP
\fB\-\-pathspec\-file\-nul\fR
.RS 4
This option is only valid for \fBcreate\fR, \fBsnatch\fR, \fBsave\fR and \fBpush\fR subcommands.
.sp
Only meaningful with \fB\-\-pathspec\-from\-file\fR. \
Pathspec elements are separated with NUL character and all other characters are taken literally (including newlines and quotes).
.RE

.PP
\fB\-\-remove\-stashed\fR
.RS 4
This option is only valid for \fBcreate\fR and \fBsave\fR subcommands and also allowed for \fBsnatch\fR and \fBpush\fR.
.sp
Changes that are included into the stash are going to be removed from the working directory.
.br
Basically, this changes \fBcreate\fR\~->\~\fBsnatch\fR and \fBsave\fR\~->\~\fBpush\fR. \
If used with \fBsnatch\fR or \fBpush\fR, this option has no effect.
.br
(This option is part of the internal mechanisms of \fBgit\~istash\fR but it's allowed to be utilised by users. \
Still, prefer using \fBsnatch\fR and \fBpush\fR for a shorter syntax and a better readability.)
.RE

.PP
\fB\-S\fR, \fB\-\-staged\fR
.RS 4
This option is only valid for \fBcreate\fR, \fBsnatch\fR, \fBsave\fR and \fBpush\fR subcommands.
.sp
All changes that are tracked but not yet added to the index are not staged and left intact. \
(It's the same as \fB\-\-leave\-staged\fR, except it targets unstaged files instead of staged ones.) \
See also \fB\-\-leave\-staged\fR.
.RE

.PP
\fB\-\-no\-store\fR
.RS 4
This option is only valid for \fBsave\fR and \fBpush\fR subcommands and also allowed for \fBcreate\fR and \fBsnatch\fR.
.sp
The stash won't be stored in the stash ref. \
Instead, its SHA will be outputted to stdout.
.br
Basically, this changes \fBsave\fR\~->\~\fBcreate\fR and \fBpush\fR\~->\~\fBsnatch\fR. \
If used with \fBcreate\fR or \fBsnatch\fR, this option has no effect.
.br
(This option is part of the internal mechanisms of \fBgit\~istash\fR but it's allowed to be utilised by users. \
Still, prefer using \fBcreate\fR and \fBsnatch\fR for a shorter syntax and a better readability.)
.RE

.PP
\fB\-u\fR, \fB\-\-include\-untracked\fR, \fB\-\-no\-include\-untracked\fR
.RS 4
This option is only valid for \fBcreate\fR, \fBsnatch\fR, \fBsave\fR and \fBpush\fR subcommands.
.sp
All untracked files are also stashed and then removed.
.br
\fB\-\-no\-include\-untracked\fR also affects \fB\-\-all\fR, resulting in stashing and removing only ignored files.
.RE

.PP
\fB\-c\fR, \fB\-\-continue\fR
.RS 4
This option is only valid for \fBapply\fR and \fBpop\fR subcommands. \
(You can skip the subcommand name in the command line.)
.sp
Resume the operation after conflicts have been resolved.
.RE

.PP
\fB\-\-abort\fR
.RS 4
This option is only valid for \fBapply\fR and \fBpop\fR subcommands. \
(You can skip the subcommand name in the command line.)
.sp
Cancel the operation and restore the repository to the state before it started.
.sp
Aborting is apply / pop agnostic. \
You can call \fBgit istash apply \-\-abort\fR on an active pop operation and it will still work correctly (and vice versa).
.RE

.PP
\fB\-\-quit\fR
.RS 4
This option is only valid for \fBapply\fR and \fBpop\fR subcommands. \
(You can skip the subcommand name in the command line.)
.sp
Cancel the operation without restoring the state of the repository. \
(In an unlikely scenario where an operation breaks for any reason, this is the most reliable way to cancel it because it doesn't require the state to be in any way valid.)
.sp
Quitting is apply / pop agnostic. \
You can call \fBgit istash apply \-\-abort\fR on an active pop operation and it will still work correctly (and vice versa).
.RE

.PP
\fB\-\-quiet\fR
.RS 4
Suppress human-readable summaries and informative text. \
This is most messages (even warnings), except for errors, machine-readable data (stash SHAs) and output related to the \fB\-\-patch\fR option.
.br
(Exit codes remain the same, unlike in some other git commands.)
.sp
This option is primarily intended for scripts. \
It speeds up the execution by skipping some operations intended only for display purposes, such as creating a stash of the previous working directory changes or generating a change summary.
.RE

.PP
\fB\-\-color[=<when>]\fR
.RS 4
Use color in output. \
\fI<when>\fR can be one of \fBalways\fR, \fBnever\fR, or \fBauto\fR. \
\fB\-\-color\fR (i.e. without \fI=<when>\fR) is the same as \fB\-\-color=always\fR.
.sp
Color can also be changed by config variables (allowing more granularity) but this option has a higher priority.
.RE

.PP
\fB\-\-no\-color\fR
.RS 4
Turn off color in output. \
It is the same as \fB\-\-color=never\fR.
.RE

.PP
\fB\-\-summary=<mode>\fR
.RS 4
This option is only valid for \fBapply\fR and \fBpop\fR subcommands.
.sp
Set how much of the post-apply summary is shown. \
(The summary looks very much like \fBgit status\fR but it shows the changes made by applying the stash instead of the current state of the working directory.)
.br
There are 3 modes:
.PD 0
.IP \(em 2
\fBcomplete\fR - shows all changed files in the working copy.
.IP \(em 2
\fBnon-ignored\fR - skips ignored files, including the ones that were ignored but aren't anymore after the operation. \
(Ignored files are the most time-consuming thing to list.)
.IP \(em 2
\fBoff\fR - doesn't display the summary at all.
.PD
.PP
Summary mode can also be changed by the config variable \fBistash.summary\fR but this option has a higher priority.
.RE

.PP
\fB\-h\fR
.RS 4
Print a rudimentary help text to stdout. \
(Each subcommand has its own text.)
.sp
This is a fallback option that is to be used when the man page is not available. \
Prefer \fBgit\~help\~istash\fR (or \fBgit\~istash\~\-\-man\fR) over \fBgit\~istash\~[<subcommand>]\~\-h\fR.
.RE

.PP
\fB\-\-help\fR
.RS 4
Display the man page for \fBgit\~istash\fR. \
(It it's not possible, fall back to \fB\-h\fR.)
.sp
Normally this option is handled by the Git itself, but this doesn't work on Windows because Git expects HTML documentation there. \
See also \fB\-\-man\fR.
.RE

.PP
\fB\-\-man\fR
.RS 4
Display the man page for \fBgit\~istash\fR. \
(It it's not possible, fall back to \fB\-h\fR.)
.sp
This is exactly the same as \fB\-\-help\fR except it doesn't get intercepted by \fBgit\fR, which makes it work correctly on Windows (if \fBman\fR is present).
.RE

.PP
\fB\-V, \-\-version\fR
.RS 4
Display version information for the script.
.RE

.PP
\fB\-\-\fR
.RS 4
Separates options from non-option arguments (like stash or pathspec) for disambiguation purposes.
.RE

.PP
\fB<pathspec>...\fR
.RS 4
This option is only valid for \fBcreate\fR, \fBsnatch\fR, \fBsave\fR and \fBpush\fR subcommands.
.sp
The new stash entry records the modified states and rolls back only for the files that match the pathspec.
.sp
For more details, see the \fIpathspec\fR entry in \fBgitglossary\fR(7).
.RE

.PP
\fB<stash>\fR
.RS 4
This option is only valid for \fBapply\fR and \fBpop\fR subcommands.
.sp
It selects a specific stash to be applied and/or dropped.
.sp
The stash can be expressed in multiple ways:
.PD 0
.IP \(em 2
An integer \(em the number of the stash in the stash ref. \
E.g. \fB0\fR is the latest stash, \fB1\fR is the one before it, etc.
.br
Negative numbers are also allowed and they are interpreted as going back from the end of the list. \
E.g. \fB-1\fR is the last (oldest) stash, \fB-2\fR is second to last, etc. \
(When the script encounters a negative number, it adds to it the total number of stashes in the stash log.)
.br
You can display the current stash log with the numbers by calling \fBgit stash list\fR.
.br
This format can be used with \fBapply\fR and \fBpop\fR.
.IP \(em 2
Full name of the stash ref entry \(em mostly equivalent to giving just the integer value. \
E.g. \fBstash@{0}\fR (or just \fBstash\fR) is the latest stash, \fBstash@{1}\fR is the one before it, etc.
.br
This notation doesn't accept negative numbers.
.br
This format can be used with \fBapply\fR and \fBpop\fR.
.IP \(em 2
Stash ref entry by message \(em finds stash entry with the given text in its message. \
E.g. \fBstash^{/aaa}\fR is the first stash from the list that has "aaa" in its description.
.br
This format can be used with \fBapply\fR and \fBpop\fR.
.IP \(em 2
Any commit with a valid stash \(em SHA, branch name or any other way to point to a specific commit in Git. \
It doesn't have to be added to the stash ref; it can be just a dangling commit, as long as it is a valid stash.
.br
This format can be used only with \fBapply\fR.
.PD
.PP
When no \fB<stash>\fR is given, the latest stash is assumed (same as \fB0\fR, \fBstash\fR or \fBstash@{0}\fR).
.RE


.SH EXIT CODES
.nf
\fB0\fR \(em command succeeded
\fB1\fR \(em command failed
\fB2\fR \(em (only \fBapply\fR and \fBpop\fR) command was stopped by a conflict and can be resumed with \fB\-\-continue\fR, aborted with \fB\-\-abort\fR or canceled with \fB\-\-quit\fR
.fi


.SH ERRORS
Errors printed by \fBistash\fR are divided into two general categories:
.PD 0
.IP \(em 2
Normal errors (prefixed with "error:") are most likely a result of a user error (such as providing an incorrect stash number).
.IP \(em 2
Fatal errors (prefixed with "fatal:") are caused by an internal error (such as missing data file or failure of another Git command).
.PD
.PP
The same prefixes are used by native Git commands but there their choice comes more to technical details than any user-facing distinction.


.SH EXAMPLES

.PP
Interrupted workflow, without losing index
.RS 4
When you are in the middle of something and you suddenly have a \fIbrilliant idea\fR for something that should be changed \fIimmediately\fR, even before the things you're working on currently. \
Traditionally, you would make a commit to a temporary branch to store your changes away, and return to your original branch to implement your awesome idea, like this:
.sp
.RS 4
.nf
# ... hack hack hack ...
$ git switch \-c my_wip
$ git commit \-a \-m "WIP"
$ git switch original_branch
# Implement the idea
$ git commit \-a \-m "Best change ever"
$ git switch my_wip
$ git rebase original_branch
$ git reset \-\-soft HEAD^
$ git branch \-D original_branch
$ git branch \-m original_branch
# ... continue hacking ...
.fi
.RE
.sp
The above is complicated and has a lot of steps that can break something if you make a mistake. \
Additionally, it doesn't preserve the index.
.sp
You can use \fBgit istash\fR to simplify it \fIand\fR keep the index intact:
.sp
.RS 4
.nf
# ... hack hack hack ...
$ git istash
# Implement the idea
$ git commit \-a \-m "Best change ever"
$ git istash pop
# ... continue hacking ...
.fi
.RE
.RE

.PP
Applying stash with conflicts both in staged and unstaged changes
.RS 4
So far, you may be thinking: \
"Why would I need a custom Git script for that since a normal stash command can do it as well?"
.br
Let's assume the same scenario as in the example above; however, this time the \fIbrilliant idea\fR involves editing some of the same lines that are currently changed.
.sp
In such situation, normal \fBgit stash\fR won't let you use the option \fB\-\-index\fR, forcing you to discard your changes in index.
.br
When \fBgit istash\fR encounters conflicts, it behaves like \fBgit rebase\fR and stops to allow the user to deal with the problem. \
(Actually, it uses \fBrebase\fR under the hood.)
.sp
.RS 4
.nf
# ... hack hack hack ...
$ git istash
# Implement the idea
$ git commit \-a \-m "Best change ever"
$ git istash pop
# (git\-istash will stop and report that some files have conflicts)
# Fix the conflicts in the index
$ git add \-u
$ git istash \-\-continue
# (git\-istash will stop and report that some files have conflicts again)
# Fix the conflicts in unstaged changes
$ git add \-u
$ git istash \-\-continue
# ... continue hacking ...
.fi
.RE
.sp
After the whole operation is finished, the stashed index is restored and intact.
.RE

.PP
Stashing away untracked files
.RS 4
You've created a few new files yet to be added to the repository but you've realized that you will need them a little later and they are getting in the way of what you're doing right now.
.sp
You would like to move them somewhere where they won't bother you for now, but keep them safe.
.sp
.RS 4
.nf
# ... hack hack hack ...
$ git istash push \-\-leave\-staged \-\-staged \-\-include\-untracked \-m 'some new files, for safe keeping'
# (or just "git istash push \-lSu")
# ... continue hacking until the files are needed ...
$ git istash pop
# ... hacking intensifies ...
.fi
.RE
.RE


.SH CONFIGURATION
Some descriptions in this section are selectively included from \fBgit\-config\fR(1) documentation. \
The content is the same as what was found there at the time of writing / updating this.
.sp
Variables with \fBistash\fR in their names are described only here.

advice.*
.RS 4
These variables control various optional help messages designed to aid new users. \
When left unconfigured, Git will give the message alongside instructions on how to squelch it. \
You can tell Git that you have understood the issue and no longer need a specific help message by setting the corresponding variable to \fBfalse\fR.
.sp
As they are intended to help human users, these messages are output to the standard error. \
When tools that run Git as a subprocess find them disruptive, they can set \fBGIT_ADVICE=0\fR in the environment to squelch all advice messages.
.sp
istashConflicts
.RS 4
Shown when \fBapply\fR/\fBpop\fR has stopped to resolve conflicts.
.RE
.sp
istashContinueOrAbort
.RS 4
Shown when trying to run a new \fBistash\fR operation while \fBapply\fR/\fBpop\fR is already running (stopped for conflicts).
.RE
.sp
istashFinalizeOther
.RS 4
Shown when trying to run \fBistash\fR while another operation (like \fBmerge\fR or \fBrebase\fR) is in progress.
.RE
.sp
istashFixOrQuit
.RS 4
Shown when \fBapply\fR/\fBpop\fR cannot resume because of problems with saved data or an illegal state of the repository.
.RE
.sp
istashHelp
.RS 4
Shown when the command was called with wrong arguments.
.RE
.sp
istashImplPushPathspec
.RS 4
Shown when trying to run \fBpush\fR implicitely without separating pathspecs from other arguments with \fB\-\-\fR.
.RE
.RE

color.advice
.RS 4
A boolean to enable/disable color in hints (e.g. when a push failed, see \fBadvice.*\fR  for a list). \
May be set to \fBalways\fR, \fBfalse\fR (or \fBnever\fR) or \fBauto\fR (or \fBtrue\fR), in which case colors are used only when the error output goes to a terminal. \
If unset, then the value of \fBcolor.ui\fR is used (\fBauto\fR by default).
.RE

color.advice.hint
.RS 4
Use customized color for hints.
.RE

color.istash
.RS 4
This variable determines the default value for variables such as \fBcolor.istash.advice\fR and \fBcolor.istash.error\fR that control the use of color by \fBistash\fR per category. \
It functions analogously to \fBcolor.ui\fR except its scope is limited to \fBistash\fR. \
If unset, then the value of \fBcolor.ui\fR is used (\fBauto\fR by default).
.RE

color.istash.advice
.RS 4
A boolean to enable/disable color in hints printed by \fBistash\fR (e.g. when a conflict occurred). \
May be set to \fBalways\fR, \fBfalse\fR (or \fBnever\fR) or \fBauto\fR (or \fBtrue\fR), in which case colors are used only when the error output goes to a terminal. \
If unset, then the value of \fBcolor.istash\fR is used, and if it is unset too \fBcolor.advice\fR is used.
.RE

color.istash.advice.hint
.RS 4
Use customized color for hints printed by \fBistash\fR. \
If unset, then the value of \fBcolor.advice.hint\fR is used (\fByellow\fR by default).
.RE

color.istash.error
.RS 4
A boolean to enable/disable color in warnings and errors printed by \fBistash\fR. \
May be set to \fBalways\fR, \fBfalse\fR (or \fBnever\fR) or \fBauto\fR (or \fBtrue\fR), in which case colors are used only when the error output goes to a terminal. \
If unset, then the value of \fBcolor.istash\fR is used.
.RE

color.istash.error.default
.RS 4
Use customized color for errors printed by \fBistash\fR.
.RE

color.istash.error.fatal
.RS 4
Use customized color for fatal errors printed by \fBistash\fR. \
If unset, then the value of \fBcolor.istash.error.default\fR is used (\fBbold red\fR by default).
.RE

color.istash.error.normal
.RS 4
Use customized color for normal (user) errors printed by \fBistash\fR. \
If unset, then the value of \fBcolor.istash.error.default\fR is used (\fBred\fR by default).
.RE

color.istash.error.warning
.RS 4
Use customized color for warning printed by \fBistash\fR. \
If unset, then it defaults to \fByellow\fR.
.RE

color.istash.summary
.RS 4
A boolean to enable/disable color of summary of changes in the output of the commands \fBapply\fR and \fBpop\fR. \
May be set to \fBalways\fR, \fBfalse\fR (or \fBnever\fR) or auto (or \fBtrue\fR), in which case colors are used only when the output is to a terminal. \
If unset, then the value of \fBcolor.istash\fR is used and if this is unset too, \fBcolor.status\fR is used.
.RE

color.istash.summary.<slot>
.RS 4
Use customized color for summary of changes in the output of the commands \fBapply\fR and \fBpop\fR. \
\fB<slot>\fR is one of \fBheader\fR (the header text of the status message), \fBadded\fR or \fBupdated\fR (files which are added but not committed), \fBchanged\fR (files which are changed but not added in the index), \fBuntracked\fR (files which are not tracked by Git). \
If unset, then the value of \fBcolor.status\fR with the same slot name is used.
.RE

color.status
.RS 4
A boolean to enable/disable color in the output of \fBgit-status\fR(1). \
May be set to \fBalways\fR, \fBfalse\fR (or \fBnever\fR) or auto (or \fBtrue\fR), in which case colors are used only when the output is to a terminal. \
If unset, then the value of \fBcolor.ui\fR is used (\fBauto\fR by default).
.RE

color.status.<slot>
.RS 4
Use customized color for status colorization. \
\fB<slot>\fR is one of \fBheader\fR (the header text of the status message), \fBadded\fR or \fBupdated\fR (files which are added but not committed), \fBchanged\fR (files which are changed but not added in the index), \fBuntracked\fR (files which are not tracked by Git), \fBbranch\fR (the current branch), \fBnobranch\fR (the color the \fIno branch\fR warning is shown in, defaulting to red), \fBlocalBranch\fR or \fBremoteBranch\fR (the local and remote branch names, respectively, when branch and tracking information is displayed in the status short-format), or \fBunmerged\fR (files which have unmerged changes).
.RE

color.ui
.RS 4
This variable determines the default value for variables such as \fBcolor.diff\fR and \fBcolor.grep\fR that control the use of color per command family. \
Its scope will expand as more commands learn configuration to set a default for the \fB\-\-color\fR option. \
Set it to \fBfalse\fR or \fBnever\fR if you prefer Git commands not to use color unless enabled explicitly with some other configuration or the \fB\-\-color\fR option. \
Set it to \fBalways\fR if you want all output not intended for machine consumption to use color, to \fBtrue\fR or \fBauto\fR (this is the default since Git 1.8.4) if you want such output to use color when written to the terminal.
.RE

istash.summary
.RS 4
This variable stores the default value for the option \fB\-\-summary\fR (when it's not given). \
If unset, it defaults to \fBcomplete\fR. \
(See \fB\-\-summary\fR for the description of all possible values.)
.RE


.SH SEE ALSO
\fBgit\-stash\fR(1), \fBgit\-rebase\fR(1)


.SH CURRENT LIMITATIONS
.PP
Changes are not removed from working directory when \fB\-\-patch\fR with \fBe\fR was used to stash only some of consecutive changed lines. \
(It will be fixed if I can figure out a way to do it in a consistent way.)
.PP
Not all subcommands present in the vanilla command are avaible here (e.g. \fBgit stash show\fR, \fBgit stash list\fR...).
.br
(However, most of the vanilla subcommands are fully or at least mostly compatible with stashes created by this commands.)
.PP
Because this command is written entirely in the shell script, it's slow. \
The advantage of this is that it can run on every system with very little additional development cost.
.br
(A few seconds to make a stash isn't that a big deal, so the command probably won't be rewritten to a faster language anytime soon.)
.PP
There's no support for running the command while there are other unfinished operations in the repository (like rebase or merge).
.PP
Option \fB\-\-patch\fR eats more stdin than it needs to. \
(This is the fault of underlying \fBgit\~add\~\-\-patch\fR.)


.SH AUTHOR
git\-istash was written by Piotr Siupa. (\fIpiotr.siupa+stash@gmail.com\fR)
.sp
The command and everything around it was strongly inspired by Git (quite obviously).
