#!/usr/bin/env sh

# Fully POSIX option parser inspired by GNU getopt, although not strictly compatible with it.
# The small deviations of the output (from what getopt with similar options would produce with similar settings) are there because of how get_options is used by the script for which it was written.
# The user should still get exactly what their expect from a GNU-like program.
# It can be either sourced or used as a standalone script.
# See, "--help" for more information.

# Escapes stdin in a way that it will be "eval"ed as a single string in a POSIX shell.
escape_for_shell() {
	printf \'
	sed -E s/\'/\'\\\\\'\'/g
	printf \'
}

# Escapes stdin in a way that it will be "eval"ed as a single string in a POSIX shell but without packing the entire string into '' (nor "").
soft_escape_for_shell() {
	{ cat ; printf 'X' ; } \
	| sed -E -e 's/[^-_[:alnum:][:blank:]]/'\''&'\''/g' \
		-e '1!s/^/'\''/' \
		-e '$!s/$/'\''/' \
		-e '$s/X$//' \
		-e 's/[[:blank:]]/\\&/g'
}

get_options() ( # See "print_help" for usage.
	set -eu
	LC_ALL=C
	export LC_ALL
	
	nl='
'
	
	fatal() { # printf_arg...
		printf 'fatal: '
		#shellcheck disable=SC2059
		printf "$@"
		printf '\n'
		return 2
	} 1>&2
	
	strip_whitespace=n
	if [ "${1-}" = '-w' ]
	then
		strip_whitespace=y
		shift
	fi
	
	single_definition=n
	if [ "${1-}" = '-s' ]
	then
		single_definition=y
		shift
	fi
	
	posixly=n
	reorder=y
	partial=n
	if [ "${1-}" = '-P' ]
	then
		posixly=y
		shift
	elif [ "${1-}" = '-R' ]
	then
		reorder=n
		shift
	elif [ "${1-}" = '-U' ]
	then
		partial=y
		shift
	fi
	
	printf '%s' "${1-}" | grep -E -q '^-' &&
		fatal 'unknown option `%s'\'' for get_options' "$1"
	
	strip_short_options_whitespace() {
		tr -d ' \t\n'
	}
	strip_long_options_whitespace() {
		#shellcheck disable=SC2016
		sed -E -n -e '1h' -e '1!H' -e '$g' \
			-e '${' \
				-e 's/^([[:blank:]]|\n)+//' \
				-e 's/([[:blank:]]|\n)+:/:/g' \
				-e 's/([[:blank:]]|\n)+,/,/g' \
				-e 's/,([[:blank:]]|\n)+/,/g' \
				-e 's/([[:blank:]]|\n)+$//' \
				-e 'p' \
			-e '}'
	}
	
	if [ "$single_definition" = n ]
	then
		
		test $# -ge 2 ||
			fatal 'not enough arguments for get_options'
		
		if [ "$strip_whitespace" = y ]
		then
			short_options_description="$(printf '%s' "$1" | strip_short_options_whitespace)"
		else
			short_options_description="$1"
		fi
		shift
		test "${short_options_description#:}" = "$short_options_description" ||
			fatal 'empty entry in short options definition for get_options'
		test "${short_options_description#*:::}" = "$short_options_description" ||
			fatal 'triple `:'\'' in short options definition for get_options'
		test "${short_options_description#*-}" = "$short_options_description" ||
			fatal '`-'\'' in short options definition for get_options'
		short_options="$(
			#shellcheck disable=SC1003
			printf '%s' "$short_options_description" \
			| tr -d ':' \
			| tr '\n' ':' \
			| sed -E 's/./&\n/g'
			printf '|'
		)"
		short_options="${short_options%|}"
		repeated_option="$(printf '%s' "$short_options" | sort | uniq -c | sed -E -n '/^[[:blank:]]*1[[:blank:]]/!s/^[[:blank:]]*[0-9]+[[:blank:]]//p' | head -n 1 | sed -E 's/$/|/' | tr ':' '\n')"
		repeated_option="${repeated_option%|}"
		test -z "$repeated_option" ||
			fatal 'option `-%s'\'' repeats in options definition for get_options' "$repeated_option"
		short_options_args="$(
			#shellcheck disable=SC1003
			printf '%s' "$short_options_description" \
			| tr '\n' 'X' \
			| sed -E 's/[^:]:*/&\'"$nl"'/g' \
			| sed -E -e 's/^.$/n/' -e 's/^.:$/y/' -e 's/^.::$/o/' \
			| tr -d '\n'
		)"
		
		if [ "$strip_whitespace" = y ]
		then
			long_options_description="$(printf '%s' "$1" | strip_long_options_whitespace)"
		else
			long_options_description="$1"
		fi
		shift
		printf '%s' "$long_options_description" | tr '\n' 'X' | grep -E -q '(^|,):*,|,:*$' &&
			fatal 'empty entry in long options definition for get_options'
		long_options="$(
			printf '%s' "$long_options_description" \
			| tr ',\n' '\n,' \
			| sed -E 's/:{1,2}$//'
			printf '|'
		)"
		long_options="${long_options%|}"
		! printf '%s' "$long_options" | grep -qE ':$' ||
			fatal 'triple `:'\'' in long options definition for get_options'
		test "${long_options#*=}" = "$long_options" ||
			fatal '`='\'' in a name of a long option in definition for get_options'
		repeated_option="$(printf '%s' "$long_options" | sort | uniq -c | sed -E -n '/^[[:blank:]]*1[[:blank:]]/!s/^[[:blank:]]*[0-9]+[[:blank:]]//p' | head -n 1 | sed -E 's/$/|/' | tr ',' '\n')"
		repeated_option="${repeated_option%|}"
		test -z "$repeated_option" ||
			fatal 'option `--%s'\'' repeats in options definition for get_options' "$repeated_option"
		long_options_args="$(
			printf '%s' "$long_options_description" \
			| tr ',\n' '\n,' \
			| sed -E -e 's/^.*[^:]$/n/' -e 's/^.*[^:]:$/y/' -e 's/^.*[^:]::$/o/' \
			| tr -d '\n'
		)"
		
	else
		
		test $# -ge 1 ||
			fatal 'not enough arguments for get_options'
		
		if [ "$strip_whitespace" = y ]
		then
			all_options_description="$(printf '%s' "$1" | strip_long_options_whitespace)"
		else
			all_options_description="$1"
		fi
		shift
		printf '%s' "$all_options_description" | tr '\n' 'X' | grep -E -q '(^|,):*,|,:*$' &&
			fatal 'empty entry in options definition for get_options'
		all_options="$(
			printf '%s' "$all_options_description" \
			| tr ',\n' '\n,' \
			| sed -E 's/:{1,2}$//'
			printf '|'
		)"
		all_options="${all_options%|}"
		repeated_option="$(printf '%s' "$all_options" | sort | uniq -c | sed -E -n '/^[[:blank:]]*1[[:blank:]]/!s/^[[:blank:]]*[0-9]+[[:blank:]]//p' | head -n 1 | sed -E 's/$/|/' | tr ',' '\n')"
		repeated_option="${repeated_option%|}"
		test -z "$repeated_option" ||
			fatal 'option `%s%s'\'' repeats in options definition for get_options' "$(printf '%s' "$repeated_option" | tr '\n' 'X' | sed -E -e 's/^.$/-/' -e 's/^.{2,}$/--/')" "$repeated_option"
		short_options="$(printf '%s' "$all_options" | sed -E '/^.$/!d' | tr ',' ':' ; printf '|')"
		short_options="${short_options%|}"
		! printf '%s' "$short_options" | grep -F -q -x '-' ||
			fatal '`-'\'' in short options definition for get_options'
		long_options="$(printf '%s' "$all_options" | sed -E '/^.$/d' ; printf '|')"
		long_options="${long_options%|}"
		! printf '%s' "$long_options" | grep -qE ':$' ||
			fatal 'triple `:'\'' in options definition for get_options'
		test "${long_options#*=}" = "$long_options" ||
			fatal '`='\'' in a name of a long option in definition for get_options'
		short_options_args="$(
			printf '%s' "$all_options_description" \
			| tr ',\n' '\n,' \
			| sed -E -e '/^.:*$/!d' -e 's/^.*[^:]$/n/' -e 's/^.*[^:]:$/y/' -e 's/^.*[^:]::$/o/' \
			| tr -d '\n'
		)"
		long_options_args="$(
			printf '%s' "$all_options_description" \
			| tr ',\n' '\n,' \
			| sed -E -e '/^.:*$/d' -e 's/^.*[^:]$/n/' -e 's/^.*[^:]:$/y/' -e 's/^.*[^:]::$/o/' \
			| tr -d '\n'
		)"
		
	fi
	
	error() { # printf_arg...
		printf 'error: '
		#shellcheck disable=SC2059
		printf "$@"
		printf '\n'
		return 1
	} 1>&2
	if [ "$reorder" = y ]
	then
		non_option_args=' --'
	fi
	while [ $# -ne 0 ]
	do
		case "$1" in
		--)
			if [ "$reorder" = n ]
			then
				printf \ \'--\'
			fi
			if [ "$partial" = n ]
			then
				shift
			fi
			break
			;;
		--*)
			option_name="${1%%=*}"
			option_name="${option_name#--}"
			converted_option_name="$(printf '%s|' "$option_name" | tr '\n' ',')"
			converted_option_name="${converted_option_name%|}"
			if ! long_option_nr="$(printf '%s\n' "$long_options" | grep -n -F -x -- "$converted_option_name")"
			then
				long_option_nr="$(printf '%s\n' "$long_options" | cut -c-${#converted_option_name} | grep -n -F -x -- "$converted_option_name")" || {
					if [ "$partial" = n ]
					then
						error 'unknown option `%s'\' "$option_name"
					else
						break
					fi
				}
				test "${long_option_nr#*"$nl"}" = "$long_option_nr" ||
					error 'ambiguous option abbreviation `%s'\' "$option_name"
			fi
			long_option_nr="${long_option_nr%%:*}"
			option_name="$(printf '%s' "$long_options" | sed -E -n "${long_option_nr}p" | tr -d '\n' | tr ',' '\n' ; printf '|')"
			option_name="${option_name%|}"
			printf ' '
			printf -- '--%s' "$option_name" | soft_escape_for_shell
			has_parameter="$(printf '%s' "$long_options_args" | cut -c"$long_option_nr")"
			case "$has_parameter" in
			y)
				printf ' '
				if [ "${1#*=}" != "$1" ]
				then
					{
						printf '%s' "$1" | head -n1 | cut -d= -f2- | tr -d '\n'
						if [ "${1#*"$nl"}" != "$1" ]
						then
							printf '\n'
							printf '%s' "$1" | tail -n+2
						fi
					} | escape_for_shell
				elif [ $# -ge 2 ]
				then
					printf '%s' "$2" | escape_for_shell
					shift
				else
					error 'option `%s'\'' requires a value' "$option_name"
				fi
				;;
			o)
				printf ' '
				if [ "${1#*=}" != "$1" ]
				then
					{
						printf '%s' "$1" | head -n1 | cut -d= -f2- | tr -d '\n'
						if [ "${1#*"$nl"}" != "$1" ]
						then
							printf '\n'
							printf '%s' "$1" | tail -n+2
						fi
					} | escape_for_shell
				else
					printf \'\'
				fi
				;;
			n)
				if [ "${1#*=}" != "$1" ]
				then
					error 'option `%s'\'' takes no value' "$option_name"
				fi
				;;
			esac
			;;
		-*)
			i=2
			was_non_option=n
			while [ ${#1} -ge $i ]
			do
				option_letter="$(printf '%s' "$1" | head -c$i | tail -c+$i ; printf '|')"
				converted_option_letter="$(printf '%s' "$option_letter" | tr '\n' ':')"
				option_letter="${option_letter%|}"
				converted_option_letter="${converted_option_letter%|}"
				short_option_nr="$(printf '%s\n' "$short_options" | grep -n -F -x -- "$converted_option_letter")" || {
					if [ "$partial" = n ]
					then
						error 'unknown switch `%s'\' "$option_letter"
					else
						non_option_args="$non_option_args $({ printf -- '-' ; printf '%s' "$1" | tail -c+$i ; } | escape_for_shell)"
						shift
						was_non_option=y
						break
					fi
				}
				printf ' '
				printf -- '-%s' "${option_letter%|}" | soft_escape_for_shell
				short_option_nr="${short_option_nr%%:*}"
				has_parameter="$(printf '%s' "$short_options_args" | cut -c"$short_option_nr")"
				if [ "$has_parameter" = y ]
				then
					printf ' '
					if [ ${#1} -gt $i ]
					then
						printf '%s' "$1" | tail -c+$((i+1)) | escape_for_shell
					elif [ $# -ge 2 ]
					then
						printf '%s' "$2" | escape_for_shell
						shift
					else
						error 'switch `%s'\'' requires a value' "${option_letter%|}"
					fi
					break
				elif [ "$has_parameter" = o ]
				then
					printf ' '
					if [ ${#1} -gt $i ]
					then
						printf '%s' "$1" | tail -c+$((i+1)) | escape_for_shell
					else
						printf \'\'
					fi
					break
				else
					i=$((i+1))
				fi
			done
			if [ "$was_non_option" = y ]
			then
				break
			fi
			;;
		*)
			if [ "$posixly" = y ]
			then
				break
			elif [ "$reorder" = y ]
			then
				non_option_args="$non_option_args $(printf '%s' "$1" | escape_for_shell)"
			else
				printf ' '
				printf '%s' "$1" | escape_for_shell
			fi
			;;
		esac
		shift
	done
	while [ $# -ne 0 ]
	do
		if [ "$reorder" = y ]
		then
			non_option_args="$non_option_args $(printf '%s' "$1" | escape_for_shell)"
		else
			printf ' '
			printf '%s' "$1" | escape_for_shell
		fi
		shift
	done
	if [ "$reorder" = y ]
	then
		printf '%s' "$non_option_args"
	fi
)

if [ "${0##*/}" = 'get_options' ]
then
	set -eu
	
	print_help() {
		printf 'A fully POSIX script for parsing options in program arguments.\n'
		printf 'It is meant to be a portable alternative when "getopt" may not be available,\nor in some rare parsing scenarios that are not supported by "getopt".\n'
		#shellcheck disable=SC2016
		printf 'The output should be generally the same as in "getopt" with analogous settings\nand it is meant to be used with "eval" to set positional parameters in shell,\nlike this: eval set -- "$output_of_get_options".\n'
		printf 'The script can be run as a standalone or it can be sourced in another script.\n'
		printf '\n'
		printf 'Usage:\t%s [-w] [-P | -R | -U] <short_opt_dsc> <long_opt_dsc> [arg...]\n' "${0##*/}"
		printf '   or:\t%s [-w] -s [-P | -R | -U] <options_description> [arg...]\n' "${0##*/}"
		printf '   or:\t%s [-h | --help | -V | --version]    (Only in standalone mode.)\n' "${0##*/}"
		printf '(Ironically, the order of arguments has to be exactly as described and the short\noptions cannot be bundled.)\n'
		printf 'Options:\n'
		printf '    -w\t- Strip whitespaces from option names - remove every space, tab and\n\t  new-line that is NOT in a middle of an option name.\n\t  (This allows formatting descriptions as multiline with indentation.)\n'
		printf '    -s\t- Single options description string.\n'
		printf '    -P\t- Posixly correct mode - after the first encountered non-option, treat\n\t  everything else as non-options. Preserve the first "--" if it'\''s after\n\t  a non-option.\n'
		printf '    -R\t- Don'\''t reorder entries by placing all non-option arguments after "--"\n\t  (normalize only) and don'\''t generate an additional "--" if not present.\n'
		printf '    -U\t- When you encounter an unrecognized option don'\''t show error but instead\n\t  treat everything from this point onward as non-options.\n\t  Preserve all "--" as non-options.\n\t  (Good for pre-parsing when not all options are known yet.)\n\t  WARNING: it assumes that there is no ambiguous abbreviations between\n\t  known and unknown option names!\n'
		printf 'Standalone mode options:\n'
		printf '    -h, --help\t\t- Print this help text end exit.\n'
		printf '    -V, --version\t- Print version information and exit.\n'
		printf '\n'
		printf '<short_opt_dsc> - a string describing all allowed short options.\n'
		printf 'Short option string contains a list of options names as individual characters,\nwithout separators. '
		printf 'A special character ":" may follow another character to\nsymbolize that the option has an argument. '
		printf 'Using double ":" instead of a single\none means that the argument is not mandatory. '
		printf 'Characters "-" and ":" may not be\nused as short option names.\n'
		printf 'E.g. "abc:d" defines options "-a", "-b", "-c" and "-d", where "-c" takes an\nargument and the other options don'\''t.\n'
		printf '(An empty string means that short options are not allowed.)\n'
		printf '\n'
		printf '<long_opt_dsc> - a string describing all known long options.\n'
		printf 'Long options are a list of option names separated with ",". '
		printf 'A special character\n":" may be placed at the end of an option name to symbolize that the option has\nan argument. '
		printf 'Using double ":" instead of a single one means that the argument is\nnot mandatory. '
		printf 'Characters "=" and "," may not be used in long option names,\nand ":" cannot end them because that would be interpreted as an argument marker.\n'
		printf 'E.g. "foo,bar:,baz" defines options "--foo", "--bar" and "--baz", where "--bar"\ntakes an argument and the other options don'\''t.\n'
		printf '(An empty string means that long options are not allowed.)\n'
		printf '\n'
		printf '<options_description> - a string describing all allowed options.\n'
		printf 'This is an alternative for <short_opt_dsc> & <long_opt_dsc> that joins them into\na single string. '
		printf 'The format is the same as for <long_opt_dsc>, except that\nsingle letter options are interpreted as short options.\n'
		printf '(The drawback is that it'\'' not possible to define a single letter long option,\nalthough single letter abbreviations still do work. '
		printf 'Also, you can'\''t have a short\noption "," in this mode, since that'\''s a delimiter character.)\n'
		printf 'The goal of this is to allow for neat grouping of different spellings of\nthe same option together, for readability (especially with "-w").\n'
		printf 'E.g. "f,foo,b:,bar:" defines options "-f", "--foo", "-b" and "--bar",\nwhere "-b" and "--bar" take an argument and the other two options don'\''t.\n'
		printf '(An empty string means that no options are allowed.)\n'
		printf '\n'
		printf 'Exit values:\n'
		printf ' - 0 - Success.\n'
		printf ' - 1 - Parse error. (normal error)\n'
		printf ' - 2 - Error with the usage of the %s itself. (fatal error)\n' "${0##*/}"
	}
	
	print_version() {
		printf 'get_options version 1.0.1\n'
		printf 'Author: Piotr Siupa'
	}
	
	if [ "${1-}" = '-h' ] || [ "${1-}" = '--help' ]
	then
		print_help
		exit 0
	elif [ "${1-}" = '-V' ] || [ "${1-}" = '--version' ]
	then
		print_version
		exit 0
	fi
	
	get_options "$@"
fi
