#!/usr/bin/env sh

set -eu

. "$(dirname "$0")/git-istash-commons"
. "$(dirname "$0")/git-istash-io"

print_help() {
	printf 'git istash pop - Improved version of "git stash pop" that can handle conflicts\n    without loosing information about the files in index.\n'
	printf '\n'
	printf 'This is only a rudimentary help text. Prefer "git help istash" if available.\n'
	printf '\n'
	printf 'Usage: git istash pop [<option>...] [<stash>]\n'
	printf '   or: git istash pop (-c | --continue | --abort | --quit)\n'
	printf '   or: git istash pop -h\n'
	printf '\n'
	printf 'Options:\n'
	printf '\t--abort\t\t- Abort the previous operation and return the repository\n\t\t\t  to the state before it started.\n'
	printf '\t--color[=<when>] - Allow use of ANSI color codes.\n\t\t\t  <when> can be one of always, never, or auto.\n\t\t\t  Omitting the argument is equivalent to always.\n'
	printf '\t--no-color\t- Same as --color=never.\n'
	printf '    -c, --continue\t- Resume the previous operation.\n\t\t\t  (Conflicts need to be resolved before that.)\n'
	printf '    -h\t\t\t- Print this help text and exit.\n'
	printf '    -q, --quiet\t\t- Suppress human-readable summaries and information.\n'
	printf '\t--quit\t\t- Abort the operation but don'\''t restore the repository\n\t\t\t  state nor move the HEAD.\n'
	printf '\t--summary=<mode> - Set summary to "complete" / "non-ignored" / "off".\n'
}

check_args_for_pop() { # max_free_args args...
	check_args 'istash pop' "$@"
}

check_data_files() { # resume abort quit
	operation_in_progress="$(find_data_files)"
	case "$operation_in_progress" in
		pop)
			if [ "$1" = y ] || [ "$2" = y ] || [ "$3" = y ] ; then return 0 ; fi
			print_error_for_data_files_check "$operation_in_progress" 'pop'
			error
			;;
		apply)
			if [ "$2" = y ] || [ "$3" = y ] ; then return 0 ; fi
			print_error_for_data_files_check "$operation_in_progress" 'pop'
			error
			;;
		error-*)
			if [ "$3" = y ] ; then return 0 ; fi
			print_error_for_data_files_check "$operation_in_progress" 'pop'
			error
			;;
		nothing)
			if [ "$1" = n ] && [ "$2" = n ] && [ "$3" = n ] ; then return 0 ; fi
			error 'no istash pop in progress\n'
			;;
	esac
}

exec_apply() { # args...
	if [ "$is_quiet" = y ]
	then
		set -- --quiet "$@"
	fi
	if [ "$summary_set" = y ]
	then
		set -- --summary="$summary_mode" "$@"
	fi
	exec sh "$lib_dir/git-istash-apply" --_called-from-pop_ "$@"
}

do_start() { # args...
	check_args_for_pop 1 "$@"
	check_data_files n n n
	exec_apply -- "$@"
}

do_continue() { # args...
	check_args_for_pop 0 "$@"
	check_data_files y n n
	exec_apply --continue
}

do_abort() { # args...
	check_args_for_pop 0 "$@"
	check_data_files n y n
	exec_apply --abort
}

do_quit() { # args...
	check_args_for_pop 0 "$@"
	check_data_files n n y
	exec_apply --quit
}

do_pop() { # args...
	if [ "$continue_set" = y ]
	then
		do_continue "$@"
	elif [ "$abort_set" = y ]
	then
		do_abort "$@"
	elif [ "$quit_set" = y ]
	then
		do_quit "$@"
	else
		do_start "$@"
	fi
}

getopt_short_options='chq'
getopt_long_options='abort,color::,no-color,continue,quiet,quit,summary:'
normalized_options="$(get_options_color "$getopt_short_options" "$getopt_long_options" "$@")"
eval set -- "$normalized_options"
is_quiet=n
abort_set=n
continue_set=n
quit_set=n
summary_set=n
while true
do
	case "$1" in
	--abort)
		abort_set=y
		;;
	--color)
		shift
		set_color_for_all "$1"
		;;
	--no-color)
		set_color_for_all 'never'
		;;
	-c|--continue)
		continue_set=y
		;;
	-h)
		print_help
		exit 0
		;;
	-q|--quiet)
		is_quiet=y
		;;
	--quit)
		quit_set=y
		;;
	--summary)
		shift
		summary_set=y
		summary_mode="$1"
		;;
	--)
		shift
		break
		;;
	esac
	shift
done
if [ $continue_set = y ] && [ $abort_set = y ] && [ $quit_set = y ]
then
	printf_error 'you can choose continue, abort or quit at your discretion but the rule is that you can only have one\n'
	help_hint 'istash pop'
	error
fi
if [ $abort_set = y ] && [ $quit_set = y ]
then
	printf_error 'either abort or quit; there is no middle road\n'
	help_hint 'istash pop'
	error
fi
if [ $continue_set = y ] && [ $abort_set = y ]
then
	printf_error 'unclear whether to continue aborting or to abort continuing\n'
	help_hint 'istash pop'
	error
fi
if [ $continue_set = y ] && [ $quit_set = y ]
then
	printf_error 'unclear whether to continue quitting or to quit continuing\n'
	help_hint 'istash pop'
	error
fi

lib_dir="$(cd "$(dirname "$0")" ; pwd)"
cd "$(git rev-parse --show-toplevel)"
stash_data_file="$(make_stash_data_file_path)"
do_pop "$@"
