#!/usr/bin/env sh

set -eu

. "$(dirname "$0")/git-istash-commons"
. "$(dirname "$0")/git-istash-io"
. "$(dirname "$0")/git-istash-vanilla-format"

print_help() {
	printf 'git-istash-make-stash - An internal script of "git istash".\n'
	printf 'If you see this, something probably went wrong.\n'
	printf '\n'
	printf 'Usage: git-istash-make-stash [<option>...]\n'
	printf '   or: git-istash-make-stash -h\n'
	printf '\n'
	printf 'Options:\n'
	printf '    -a, --all\t\t- Stash and clean also untracked and ignored files.\n'
	printf '\t--allow-empty\t- Create a stash even if there are no suitable changes.\n'
	printf '\t--color[=<when>] - Allow use of ANSI color codes.\n\t\t\t  <when> can be one of always, never, or auto.\n\t\t\t  Omitting the argument is equivalent to always.\n'
	printf '\t--no-color\t- Same as --color=never.\n'
	printf '    -h\t\t\t- Print this help text and exit.\n'
	printf '    -k, --keep-index\t- Left intact all changes already added to the index.\n'
	printf '\t--no-keep-index\t- Cancel --keep-index.\n'
	printf '    -I, --skip-index\t- Left intact all changes already added to the index\n\t\t\t  and don'\''t add them to stash.\n'
	printf '    -m, --message=MSG\t- Set stash description.\n'
	printf '\t--patch\t\t- Interactively select non-staged chunks to stash.\n'
	printf '\t--pathspec-from-file=FILE - Read pathspec from the specified file.\n'
	printf '\t--pathspec-file-nul - Treat the pathspec file as NUL-separated.\n\t\t\t  (Only valid with --pathspec-from-file.)\n'
	printf '    -q, --quiet\t\t- Suppress human-readable summaries and information.\n'
	printf '\t--remove-stashed - Removes stashed changes unless there'\''s another option\n\t\t\t  to explicitely keep them.\n'
	printf '    -T, --skip-tracked\t- Left intact all changes NOT already added to the index\n\t\t\t  and don'\''t add them to stash.\n'
	printf '\t--no-store\t- Don'\''t store the created stash with "git stash store".\n\t\t\t  Instead write its sha to stdout.\n'
	printf '    -u, --untracked\t- Stash and clean also untracked files.\n'
	printf '\t--skip-untracked - Do not touch untracked files even with --all.\n'
}

convert_pathspec_file() {
	if [ "$pathspec_file_nul" = y ]
	then
		cat
	else
		#shellcheck disable=SC1003,SC2031
		convert_to_octal \
		| sed -E 's/(\\042(\\(0[0-35-7][0-7]|04[0-13-7]|1[0-24-7][0-7]|13[0-35-7]|[2-3][0-7]{2}|134\\[0-7]{1,3}))*\\042|(\\(0[02-7][0-7]|01[13-7]|[1-3][0-7]{2}))*)((\\015)?\\012|$)/\1\'"$nl"'/g' \
		| relax_octal_sanitization \
		| sed -E -e 's/\\015$//' \
			-e 's/^"(.*)"$/\1/' \
			-e 't end' \
			-e 's/\\/\\\\/g' \
			-e ':end' \
		| tr '\n' '\0' \
		| xargs -0 -r -- printf '%b\0' \
		| xargs -0 -r -- printf '%b\0'
	fi
}

initialize_commit_layout() {
	if [ "$include_ignored" = y ] || [ "$include_untracked" = y ]
	then
		has_3_commits=y
	else
		has_3_commits=n
	fi
}
initialize_pathspec_file_path() {
	pathspec_file="$(git rev-parse --git-dir)/ISTASH_PATHSPEC"
}
initialize_pathspec() { # pathspecs
	initialize_pathspec_file_path
	if [ "$pathspec_from_file" = '-' ]
	then
		convert_pathspec_file >"$pathspec_file"
	elif [ -n "$pathspec_from_file" ]
	then
		convert_pathspec_file <"$pathspec_from_file" >"$pathspec_file"
	elif [ $# -ne 0 ]
	then
		printf '%s\0' "$@" >"$pathspec_file"
	else
		pathspec_file=''
	fi
}
initialize() { # pathspecs
	initialize_commit_layout
	initialize_pathspec "$@"
}
cleanup() {
	initialize_pathspec_file_path
	if [ -n "$pathspec_file" ]
	then
		rm -f "$pathspec_file"
	fi
}

is_pathspec_exclude() { # pathspec
	if parse_git_bool "${GIT_LITERAL_PATHSPECS-}"
	then
		return 1
	fi
	printf '%s' "$1" | grep -qE '^:([!^]:?|\(([^()]+,)?exclude(,[^()]+)?\))'
}

check_pathspec() {
	if [ -n "$pathspec_file" ]
	then
		convert_to_octal_lines <"$pathspec_file" \
		| relax_octal_sanitization \
		| while read -r ps || [ -n "$ps" ]
		do
			good=n
			if is_pathspec_exclude "$ps"
			then
				good=y
			elif printf '%b' "$ps" | xargs -0 -- git commit --dry-run --short --quiet -- 1>/dev/null 2>&1
			then
				good=y
			elif [ "$has_3_commits" = y ] && printf '%b' "$ps" | xargs -0 -- git ls-files --others --error-unmatch -- 1>/dev/null 2>&1
			then
				good=y
				if [ "$include_ignored" = n ] && ! printf '%b' "$ps" | xargs -0 -- git ls-files --others --exclude-standard --error-unmatch -- 1>/dev/null 2>&1
				then
					good=n
				elif [ "$include_untracked" = n ] && [ "$(printf '%b' "$ps" | xargs -0 -- git ls-files --others -z -- | tr -cd '\0' | wc -c)" -eq "$(printf '%b' "$ps" | xargs -0 -- git ls-files --others --exclude-standard -z -- | tr -cd '\0' | wc -c)" ] 2>/dev/null
				then
					good=n
				fi
			fi
			if [ "$good" = n ]
			then
				error 'pathspec '\'"$ps"\'' did not match any file(s)\n'
			fi
		done
	fi
}

add_with_pathspec() {
	convert_to_octal_lines <"$pathspec_file" \
	| relax_octal_sanitization \
	| while read -r ps || [ -n "$ps" ]
	do
		if is_pathspec_exclude "$ps" || printf '%b' "$ps" | xargs -0 -- git add --update --dry-run -- 1>/dev/null 2>&1
		then
			printf '%b\0' "$ps"
		fi
	done \
	| xargs -r0 -- git add --update --ignore-errors -- #TODO "--ignore-errors" is temporary - there is a regression in Git
}

add_with_patch_and_pathspec() {
	exec 3<&0
	convert_to_octal_lines <"$pathspec_file" \
	| relax_octal_sanitization \
	| while read -r ps || [ -n "$ps" ]
	do
		if is_pathspec_exclude "$ps" || printf '%b' "$ps" | xargs -0 -- git add --update --dry-run -- 1>/dev/null 2>&1
		then
			printf '%b\0' "$ps"
		fi
	done \
	| xargs -r0 -- sh -c 'git add --update --patch -- "$@" <&3 1>&2' --
	exec 3<&-
}

commit_changes() {
	# initialization
	default_message="$(git rev-list --no-commit-header --format='%h %s' --max-count=1 HEAD)"
	if [ "$curr_branch_type" != 'detached' ]
	then
		branch_name_for_msg="$(git branch --show-current)"
	else
		branch_name_for_msg='(no branch)'
	fi
	there_are_enough_changes="$allow_empty"
	there_was_patch_message=n
	
	# staged (initial)
	git commit --message="index on $branch_name_for_msg: $default_message (unfinished)" --allow-empty 1>/dev/null
	
	# unstaged
	if [ "$leave_unstaged" = n ]
	then
		if [ -n "$patch_options" ]
		then
			printf '### Using the interactive patch for tracked files...\n' 1>&2
			there_was_patch_message=y
		fi
		#shellcheck disable=SC1003,SC2031
		if [ -z "$pathspec_file" ]
		then
			git --no-literal-pathspecs add --update $patch_options :/ 1>&2 2>/dev/null || true
		else
			if [ -z "$patch_options" ]
			then
				add_with_pathspec
			else
				add_with_patch_and_pathspec
			fi
		fi 2>&1 | sed -E '1s/^/\'"$nl"'/' 1>&2
	fi
	if [ -n "$message" ]
	then
		git commit --message="On $branch_name_for_msg: $message" --allow-empty 1>/dev/null
	else
		git commit --message="WIP on $branch_name_for_msg: $default_message" --allow-empty 1>/dev/null
	fi
	if [ "$there_are_enough_changes" = n ] && [ "$(git rev-parse 'HEAD^{tree}')" != "$(git rev-parse 'HEAD~^{tree}')" ]
	then
		there_are_enough_changes=y
	fi
	git --no-literal-pathspecs add --update :/ 2>/dev/null || true
	git commit --message="non-stashed WIP on $branch_name_for_msg: $default_message" --allow-empty 1>/dev/null
	
	# untracked
	if [ "$has_3_commits" = y ]
	then
		if [ "$include_untracked" = n ]
		then
			git --no-literal-pathspecs ls-files --exclude-standard --others --ignored -z :/ \
			| xargs -r0 -- git --literal-pathspecs add --force --intent-to-add --
		elif [ "$include_ignored" = n ]
		then
			git --no-literal-pathspecs add --all --intent-to-add :/ 2>/dev/null || true
		else
			git --no-literal-pathspecs add --all --force --intent-to-add :/ 2>/dev/null || true
		fi
		if [ -n "$patch_options" ]
		then
			if [ "$there_was_patch_message" = y ]
			then
				printf '\n\n' 1>&2
			fi
			printf '### Using the interactive patch for untracked files...\n' 1>&2
			there_was_patch_message=y
		fi
		#shellcheck disable=SC1003,SC2031
		if [ -z "$pathspec_file" ]
		then
			git --no-literal-pathspecs add $patch_options --update :/ 1>&2 2>/dev/null || true
		else
			if [ -z "$patch_options" ]
			then
				add_with_pathspec
			else
				add_with_patch_and_pathspec
			fi
		fi 2>&1 | sed -E '1s/^/\'"$nl"'/' 1>&2
		git commit --message="untracked files on $branch_name_for_msg: $default_message" --allow-empty 1>/dev/null
		if [ "$there_are_enough_changes" = n ] && [ "$(git rev-parse 'HEAD^{tree}')" != "$(git rev-parse 'HEAD~^{tree}')" ]
		then
			there_are_enough_changes=y
		fi
	fi
	git --no-literal-pathspecs add :/ 2>/dev/null || true
	git commit --message="non-stashed untracked files on $branch_name_for_msg: $default_message" --allow-empty 1>/dev/null
	
	# staged (for real)
	index_editor="sh -c '
		x=\"\$(cat \"\$1\")\"
		printf '%s\\n' \"\$x\" \\
		| sed -E \"1 s/^([[:blank:]]*)[[:alpha:]]+([[:blank:]])/\\1edit\\2/\" \\
		>\"\$1\"
		' _"
	if [ "$has_3_commits" = n ]
	then
		GIT_SEQUENCE_EDITOR="$index_editor" git rebase --quiet --interactive --keep-empty --empty=keep --reapply-cherry-picks -- 'HEAD~4' 1>/dev/null 2>&1
	else
		GIT_SEQUENCE_EDITOR="$index_editor" git rebase --quiet --interactive --keep-empty --empty=keep --reapply-cherry-picks -- 'HEAD~5' 1>/dev/null 2>&1
	fi
	git reset --soft 'HEAD^' 1>/dev/null
	if [ "$leave_staged" = n ]
	then
		if [ -z "$pathspec_file" ]
		then
			git commit --message="index on $branch_name_for_msg: $default_message" --allow-empty 1>/dev/null
		else
			base_commit_sha="$(git rev-parse HEAD)"
			xargs -r0 -- git diff --name-only HEAD --cached -z -- <"$pathspec_file" \
			| (
				cd "$(git rev-parse --show-toplevel)"
				xargs -r0 -- git --literal-pathspecs commit --message="index on $branch_name_for_msg: $default_message" --allow-empty -- 1>/dev/null
			)
			if [ "$(git rev-parse HEAD)" = "$base_commit_sha" ]
			then
				index_commit_sha="$(git commit-tree 'HEAD^{tree}' -p 'HEAD' -m "index on $branch_name_for_msg: $default_message")"
				git reset --soft "$index_commit_sha" 1>/dev/null
			fi
		fi
	else
		index_commit_sha="$(git commit-tree 'HEAD^{tree}' -p 'HEAD' -m "index on $branch_name_for_msg: $default_message")"
		git reset --soft "$index_commit_sha" 1>/dev/null
	fi
	if [ "$there_are_enough_changes" = n ] && [ "$(git rev-parse 'HEAD^{tree}')" != "$(git rev-parse 'HEAD~^{tree}')" ]
	then
		there_are_enough_changes=y
	fi
	git commit --message="non-stashed index on $branch_name_for_msg: $default_message" --allow-empty 1>/dev/null
	git rebase --continue 1>/dev/null
	
	# check for empty
	if [ "$there_are_enough_changes" = n ]
	then
		undo_commit_changes
		if [ "$there_was_patch_message" = y ]
		then
			printf '\n\n' 1>&2
		fi
		error 'no suitable changes to stash\n'
	fi
}
undo_commit_changes() {
	if [ "$has_3_commits" = y ]
	then
		non_staged_changes_sha="$(git rev-parse HEAD~2)"
		git reset --mixed HEAD~4 1>/dev/null
	else
		non_staged_changes_sha="$(git rev-parse HEAD~1)"
		git reset --mixed HEAD~3 1>/dev/null
	fi
	git --no-literal-pathspecs ls-tree -r --name-only "$non_staged_changes_sha" -z :/ \
	| xargs -r0 -- git --literal-pathspecs add --force --intent-to-add --
	git reset --soft HEAD~2 1>/dev/null
	if [ "$curr_branch_type" = 'orphan' ]
	then
		remove_temporary_branch
	fi
}

handle_rebase_conflict_using_theirs() {
	while true
	do
		if [ -z "$(git --no-literal-pathspecs ls-files --unmerged :/)" ]
		then
			fatal
		fi
		git --no-literal-pathspecs ls-files --unmerged --format='%(path)' -z :/ | xargs -0 -- git --literal-pathspecs restore --theirs --
		git --no-literal-pathspecs add :/ 2>/dev/null || true
		if GIT_EDITOR='true' git rebase --continue 1>/dev/null 2>&1
		then
			break
		fi
	done
}

sort_commits() {
	stashed_commits_editor="sh -c '
		x=\"\$(cat \"\$1\")\"
		printf '%s\\n' \"\$x\" \\
		| sed -En -e \"1 p\" -e \"3 p\""
	unstashed_commits_editor="sh -c '
		x=\"\$(cat \"\$1\")\"
		printf '%s\\n' \"\$x\" \\
		| sed -E"
	if [ "$has_3_commits" = y ]
	then
		stashed_commits_editor="$stashed_commits_editor -e \"5 p\""
	fi
	if [ "$remove_stashed" = n ]
	then
		unstashed_commits_editor="$unstashed_commits_editor -e \"2 s/^pick\\\\>/fixup/\" -e \"4 s/^pick\\\\>/fixup/\""
		if [ "$has_3_commits" = y ]
		then
			unstashed_commits_editor="$unstashed_commits_editor -e \"6 s/^pick\\\\>/fixup/\""
		fi
	else
		unstashed_commits_editor="$unstashed_commits_editor -n -e \"1 p\" -e \"2 p\" -e \"4 p\""
		if [ "$has_3_commits" = y ]
		then
			unstashed_commits_editor="$unstashed_commits_editor -e \"6 p\""
		else
			unstashed_commits_editor="$unstashed_commits_editor -e \"5 p\""
		fi
	fi
	stashed_commits_editor="$stashed_commits_editor \\
		>\"\$1\"
		' _"
	unstashed_commits_editor="$unstashed_commits_editor \\
		>\"\$1\"
		' _"
	
	last_commit_sha="$(git rev-parse HEAD)"
	if ! GIT_SEQUENCE_EDITOR="$unstashed_commits_editor" git -c merge.renames=false rebase --quiet --strategy=recursive --interactive --keep-empty --empty=keep --reapply-cherry-picks --strategy-option=theirs -- "$stash_base_sha" 1>/dev/null 2>&1
	then
		handle_rebase_conflict_using_theirs
	fi
	if [ "$remove_stashed" = y ]
	then
		keep_index_editor="sh -c '
			x=\"\$(cat \"\$1\")\"
			printf '%s\\n' \"\$x\" \\
			| sed -E"
		if [ "$keep_index" = n ]
		then
			keep_index_editor="$keep_index_editor -e \"1 d\""
		else
			keep_index_editor="$keep_index_editor -e \"2 s/^pick\\\\>/fixup/\""
		fi
		keep_index_editor="$keep_index_editor \\
			>\"\$1\"
			' _"
		if ! GIT_SEQUENCE_EDITOR="$keep_index_editor" git -c merge.renames=false rebase --quiet --strategy=recursive --interactive --keep-empty --empty=keep --reapply-cherry-picks --strategy-option=theirs -- "$stash_base_sha" 1>/dev/null 2>&1
		then
			handle_rebase_conflict_using_theirs
		fi
	fi
	unstashed_changes_sha="$(git rev-parse HEAD)"
	
	git switch --quiet --detach "$last_commit_sha"
	if ! GIT_SEQUENCE_EDITOR="$stashed_commits_editor" git -c merge.renames=false rebase --quiet --strategy=recursive --interactive --keep-empty --empty=keep --reapply-cherry-picks --strategy-option=theirs -- "$stash_base_sha" 1>/dev/null 2>&1
	then
		handle_rebase_conflict_using_theirs
	fi
}

handle_stash_sha() { # stash_sha
	if [ "$store_stash" = y ]
	then
		git stash store "$1" --message="$(git show -s --format=%B "$1")"
	else
		printf '%s\n' "$1"
	fi
}

restore_working_tree() {
	git switch --quiet --detach "$unstashed_changes_sha"
	unstaged_commit_sha="$(git rev-parse 'HEAD~')"
	git reset --mixed HEAD~2 1>/dev/null
	(
		cd "$(git rev-parse --show-toplevel)"
		git --no-literal-pathspecs diff-tree -r --diff-filter='A' --name-only --no-renames --no-commit-id -z "$unstaged_commit_sha~1" "$unstaged_commit_sha" -- :/ \
		| xargs -r0 -- git --literal-pathspecs add --force --intent-to-add --
	)
	git reset --soft HEAD~1 1>/dev/null
}

create_stash() {
	stash_base_sha="$(git rev-parse HEAD)"
	commit_changes
	sort_commits
	stash_sha="$(tangle_stash HEAD "$has_3_commits")"
	handle_stash_sha "$stash_sha"
	restore_working_tree
}

create_temporary_branch() {
	git --no-literal-pathspecs commit --message="Base commit for stash entry on an orphan branch \"$current_branch\"" --allow-empty --no-verify --only 1>/dev/null
}

restore_branch() {
	git switch --quiet --force-create "$current_branch" HEAD
}

remove_temporary_branch() {
	git switch --quiet --detach HEAD
	git branch --delete --force "$current_branch" 1>/dev/null
	git switch --quiet --orphan "$current_branch"
}

print_summary() {
	if [ "$is_quiet" = y ]
	then
		return
	fi
	if [ "$there_was_patch_message" = y ]
	then
		printf '\n\n' 1>&2
	fi
	printf 'Saved '
	{
		if [ "$leave_unstaged" = n ]
		then
			printf 'working directory, '
		fi
		if [ "$leave_staged" = n ]
		then
			printf 'index state, '
		fi
		if [ "$include_untracked" = y ]
		then
			printf 'untracked files'
			if [ "$include_ignored" = y ]
			then
				printf ' (including ignored)'
			fi
			printf ', '
		elif [ "$include_ignored" = y ]
		then
			printf 'ignored files, '
		fi
		if [ "$leave_unstaged" = y ] && [ "$leave_staged" = y ] && [ "$include_untracked" = n ] && [ "$include_ignored" = n ]
		then
			printf 'nothing, '
		fi
	} | sed -E -e 's/, $/ /' -e 's/,([^,]+)$/ and\1/'
	git rev-list --no-commit-header --format='%s' --max-count=1 "$stash_sha"
} 1>&2

make_stash() { # pathspecs...
	check_data_files "$command_name"
	check_other_git_commands_state
	
	initialize "$@"
	find_current_branch
	check_pathspec
	if [ "$curr_branch_type" = 'normal' ]
	then
		create_stash
		restore_branch
	elif [ "$curr_branch_type" = 'orphan' ]
	then
		create_temporary_branch
		create_stash
		remove_temporary_branch
	else
		create_stash
	fi
	print_summary
}

getopt_short_options='ahklIm:qSTu'
getopt_long_options='all,allow-empty,color::,no-color,keep-index,no-keep-index,skip-index,leave-index,no-include-index,skip-staged,leave-staged,no-include-staged,message:,patch,pathspec-file-null,pathspec-from-file:,quiet,remove-stashed,skip-tracked,leave-tracked,no-include-tracked,skip-unstaged,leave-unstaged,no-include-unstaged,staged,no-store,untracked,include-untracked,skip-untracked,leave-untracked,no-include-untracked'
normalized_options="$(get_options_color "$getopt_short_options" "$getopt_long_options" "$@")"
eval set -- "$normalized_options"
include_ignored=n
allow_empty=n
keep_index=n
leave_staged=n
message=''
patch_options=''
pathspec_from_file=''
pathspec_file_nul=n
is_quiet=n
remove_stashed=n
store_stash=y
leave_unstaged=n
include_untracked=d
while true
do
	case "$1" in
	-a|--all)
		include_ignored=y
		if [ "$include_untracked" = d ]
		then
			include_untracked=y
		fi
		;;
	--allow-empty)
		allow_empty=y
		;;
	--color)
		shift
		set_color_for_all "$1"
		;;
	--no-color)
		set_color_for_all 'never'
		;;
	-h)
		print_help
		exit 0
		;;
	-k|--keep-index)
		keep_index=y
		;;
	--no-keep-index)
		keep_index=n
		;;
	-l|-I|--skip-index|--leave-index|--no-include-index|--skip-staged|--leave-staged|--no-include-staged)
		leave_staged=y
		;;
	-m|--message)
		shift
		message="$1"
		;;
	--patch)
		patch_options='--patch'
		;;
	--pathspec-from-file)
		shift
		pathspec_from_file="$1"
		;;
	--pathspec-file-null)
		pathspec_file_nul=y
		;;
	-q|--quiet)
		is_quiet=y
		;;
	--remove-stashed)
		remove_stashed=y
		;;
	-S|-T|--skip-tracked|--leave-tracked|--no-include-tracked|--skip-unstaged|--leave-unstaged|--no-include-unstaged|--staged)
		leave_unstaged=y
		;;
	--no-store)
		store_stash=n
		;;
	-u|--untracked|--include-untracked)
		include_untracked=y
		;;
	--skip-untracked|--leave-untracked|--no-include-untracked)
		include_untracked=n
		;;
	--)
		shift
		break
		;;
	esac
	shift
done
if [ "$include_untracked" = d ]
then
	include_untracked=n
fi
if [ -n "$patch_options" ] && [ "$pathspec_from_file" = '-' ]
then
	error 'stdin cannot be assigned to both '\''--patch'\'' and the pathspec\n'
fi
if [ -z "$pathspec_from_file" ] && [ "$pathspec_file_nul" = y ]
then
	error 'option '\''--pathspec-file-nul'\'' is not valid without '\''--pathspec-from-file'\''\n'
fi
command_name="$1"
shift

set +e
(
	set -e
	make_stash "$@"
)
exit_code=$?
set -e
cleanup
exit $exit_code
