#!/usr/bin/env sh

set -eu

. "$(dirname "$0")/git-istash-commons"
. "$(dirname "$0")/git-istash-vanilla-format"

print_help() {
	printf 'git istash apply - Improved version of "git stash apply" that can handle\n    conflicts without loosing information about the files in index.\n'
	printf '\n'
	printf 'This is only a rudimentary help text. Prefer "git help istash" if available.\n'
	printf '\n'
	printf 'Usage: git istash apply [<option>...] [<stash>]\n'
	printf '   or: git istash apply (-c | --continue | --abort | --quit)\n'
	printf '   or: git istash apply -h\n'
	printf '\n'
	printf 'Options:\n'
	printf '\t--abort\t\t- Abort the previous operation and return the repository\n\t\t\t  to the state before it started.\n'
	printf '    -c, --continue\t- Resume the previous operation.\n\t\t\t  (Conflicts need to be resolved before that.)\n'
	printf '    -h\t\t\t- Show this help text and exit.\n'
	printf '\t--quit\t\t- Abort the operation but don'\''t restore the repository\n\t\t\t  state nor move the HEAD.\n'
}

get_sub_command_name() {
	if [ "$is_pop" = n ]
	then
		printf 'apply'
	else
		printf 'pop'
	fi
}

save_data() {
	target_data="$(if [ "$curr_branch_type" = 'orphan' ] ; then printf '~' ; fi ; printf '%s' "$current_branch")"
	printf '%s\n' "$target_data" >"$target_data_file"
	
	printf '%s\n' "$working_dir_changes_sha" >"$working_dir_sha_file"
}
load_target_data() { # subcommand
	if [ "$(wc -l <"$target_data_file")" -ne 1 ]
	then
		printf 'fatal: '\''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)" 1>&2
		printf 'fatal: '\''%s'\'' doesn'\''t have exactly 1 line\n' "$target_data_file" 1>&2
		print_broken_operation_hint "$1"
		return 1
	fi
	current_branch="$(cat "$target_data_file")"
	if printf '%s' "$current_branch" | grep -qE '^~'
	then
		current_branch="$(printf '%s' "$current_branch" | cut -c2-)"
		curr_branch_type='orphan'
	else
		curr_branch_type='normal'
	fi
	if ! git rev-parse --quiet --verify "$current_branch^{commit}" 1>/dev/null
	then
		printf 'fatal: '\''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)" 1>&2
		printf 'fatal: '\''%s'\'' contains an invalid commit hash\n' "$target_data_file" 1>&2
		print_broken_operation_hint "$1"
		return 1
	fi
	if [ "$curr_branch_type" != 'orphan' ] && [ "$(git rev-parse "$current_branch")" = "$current_branch" ]
	then
		curr_branch_type='detached'
	fi
}
load_working_dir_data() { # subcommand
	if [ "$(wc -l <"$working_dir_sha_file")" -ne 1 ]
	then
		printf 'fatal: '\''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)" 1>&2
		printf 'fatal: '\''%s'\'' doesn'\''t have exactly 1 line\n' "$working_dir_sha_file" 1>&2
		print_broken_operation_hint "$1"
		return 1
	fi
	working_dir_changes_sha="$(cat "$working_dir_sha_file")"
	if ! git rev-parse --quiet --verify "$working_dir_changes_sha^{commit}" 1>/dev/null
	then
		printf 'fatal: '\''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)" 1>&2
		printf 'fatal: '\''%s'\'' contains an invalid commit hash\n' "$working_dir_sha_file" 1>&2
		print_broken_operation_hint "$1"
		return 1
	fi
}
load_data() { # subcommand
	load_target_data "$1"
	load_working_dir_data "$1"
}
delete_data() {
	rm -f "$target_data_file" "$working_dir_sha_file"
}

check_args_for_apply() { # max_free_args args...
	check_args 'istash apply' "$@"
}

put_files_into_working_copy() { # untracked_changes_sha non_staged_changes_sha staged_changes_sha
	git restore --quiet --source="$3" -- . 2>/dev/null || true
	git add -- .
	git restore --quiet --source="$1" -- . 2>/dev/null || true
	git --no-literal-pathspecs ls-tree -r --name-only "$2" -z :/ \
	| xargs -r0 -- git --literal-pathspecs add --intent-to-add --
}

end_with_rebase_problem() {
	{
		printf_color 2 '\033[33m'
		sub_command_name="$(get_sub_command_name)"
		printf 'hint: use '\''git istash --continue'\'' after fixing the conflicts\n'
		printf 'hint: or, to undo everything '\''git istash %s'\'' did, run '\''git istash --abort'\''\n' "$sub_command_name"
		printf_color 2 '\033[39m'
	} 1>&2
	return 2
}
end_with_success() {
	if { [ "$curr_branch_type" != 'orphan' ] && [ "$(git rev-parse HEAD~6)" != "$(git rev-parse "$current_branch")" ] ; } \
		|| { [ "$curr_branch_type" = 'orphan' ] && [ "$(git rev-list --no-walk --count HEAD~6^@)" != '0' ] ; }
	then
		printf 'fatal: HEAD is not in the correct position after rebasing\n' 1>&2
		return 1
	fi
	untracked_changes_sha="$(git rev-parse HEAD~0)"
	non_staged_changes_sha="$(git rev-parse HEAD~2)"
	staged_changes_sha="$(git rev-parse HEAD~4)"
	case "$curr_branch_type" in
		orphan)
			if [ -n "$(git ls-tree -r --name-only HEAD~6)" ]
			then
				# This error is untested because it's hard to come up with a scenario so contrived that it would occur.
				printf 'fatal: the empty commit created for the command is not empty\n' 1>&2
				return 1
			fi
			git branch --quiet --delete --force "$current_branch"
			git switch --quiet --orphan "$current_branch"
			;;
		normal)
			git switch --quiet "$current_branch"
			;;
		detached)
			git switch --quiet --detach HEAD~6
			;;
	esac
	put_files_into_working_copy "$untracked_changes_sha" "$non_staged_changes_sha" "$staged_changes_sha"
	delete_data
	printf 'Stash of the old working dir: %s\n' "$(prepare_stash_of_working_dir)"
	if [ "$is_pop" = n ]
	then
		printf '\nSuccessfully applied the stash\n'
	fi
}

check_data_files() { # resume quit
	if [ "$is_pop" = y ] ; then return 0 ; fi
	operation_in_progress="$(find_data_files)"
	case "$operation_in_progress" in
		pop)
			if [ "$2" = y ] ; then return 0 ; fi
			print_error_for_data_files_check "$operation_in_progress" 'apply'
			return 1
			;;
		apply)
			if [ "$1" = y ] || [ "$2" = y ] ; then return 0 ; fi
			print_error_for_data_files_check "$operation_in_progress" 'apply'
			return 1
			;;
		error-*)
			if [ "$2" = y ] ; then return 0 ; fi
			print_error_for_data_files_check "$operation_in_progress" 'apply'
			return 1
			;;
		nothing)
			if [ "$1" = n ] && [ "$2" = n ] ; then return 0 ; fi
			printf 'error: no istash apply in progress\n' 1>&2
			return 1
			;;
	esac
}

prepare_current_branch() {
	if [ "$curr_branch_type" = 'orphan' ]
	then
		git commit --quiet --only --allow-empty --message 'Temporary commit by "git-stash"'
	fi
}

commit_working_directory() {
	# initialization
	default_message="$(git rev-list --no-commit-header --format='%h %s' --max-count=1 HEAD)"
	message="Working directory changes prior to applying stash $(git rev-parse "$(get_stash_commit "$stash")")"
	if [ "$curr_branch_type" != 'detached' ]
	then
		branch_name_for_msg="$(git branch --show-current)"
	else
		branch_name_for_msg='(no branch)'
	fi
	git switch --quiet --detach HEAD
	
	# staged
	git commit --quiet --message="index on $branch_name_for_msg: $default_message" --allow-empty
	
	# unstaged
	git --no-literal-pathspecs add --update :/ 1>&2 2>/dev/null || true
	git commit --quiet --message="On $branch_name_for_msg: $message" --allow-empty
	
	# untracked
	git --no-literal-pathspecs add --all --intent-to-add :/ 2>/dev/null || true
	git --no-literal-pathspecs add --update :/ 1>&2 2>/dev/null || true
	git commit --quiet --message="untracked files on $branch_name_for_msg: $default_message" --allow-empty
	
	# save sha
	working_dir_changes_sha="$(git rev-parse 'HEAD')"
}

prepare_stash_of_working_dir() {
	if [ "$(git rev-parse "$working_dir_changes_sha^{tree}")" = "$(git rev-parse "$working_dir_changes_sha~1^{tree}")" ]
	then
		tangle_stash "$working_dir_changes_sha~1" n
	else
		tangle_stash "$working_dir_changes_sha" y
	fi
}

start_rebase() { # untangled_stash_sha
	todo_list_editor="sed -i -E \
			-e '1 i pick $working_dir_changes_sha~2 Staged working directory' \
			-e '2 i pick $working_dir_changes_sha~1 Unstaged working directory' \
			-e '3 i pick $working_dir_changes_sha~0 Untracked working directory'"
	if GIT_EDITOR="$todo_list_editor" git rebase --onto "$current_branch" "$1~3" "$1" --empty=keep --keep-empty --reapply-cherry-picks --interactive 2>/dev/null
	then
		end_with_success
	elif are_there_conflicts
	then
		end_with_rebase_problem
	else
		do_abort
		return 1
	fi
}

do_start() { # args...
	check_args_for_apply 1 "$@"
	check_data_files n n
	check_other_git_commands_state
	find_stash "$@"
	find_current_branch
	prepare_current_branch
	commit_working_directory
	save_data
	stash_sha="$(get_stash_commit "$stash")"
	untangled_stash_sha="$(untangle_git_stash "$stash_sha")"
	start_rebase "$untangled_stash_sha"
}

do_continue() { # args...
	check_args_for_apply 0 "$@"
	check_data_files y n
	load_data "$(get_sub_command_name)"
	
	git commit --quiet --allow-empty --no-edit 1>/dev/null 2>&1 || true
	exec 3>&1
	if stderr="$(git -c 'core.editor=true' rebase --continue 2>&1 1>&3)"
	then
		end_with_success
	elif are_there_conflicts
	then
		end_with_rebase_problem
	else
		exec 3>&-
		printf '%s\n' "$stderr" 1>&2
		git reset --quiet --soft HEAD~
		return 1
	fi
	exec 3>&-
}

do_abort() { # args...
	check_args_for_apply 0 "$@"
	check_data_files y n
	load_data "$(get_sub_command_name)"
	
	git rebase --abort || true  # Errors are ignored because if rebase is not in progress, we still want to try to restore HEAD.
	git reset --quiet --hard
	succeeded_switch=n
	exec 3>&1
	case "$curr_branch_type" in
		orphan)
			git branch --quiet --delete --force "$current_branch"
			if error_message="$(git switch --quiet --orphan "$current_branch" 2>&1 1>&3)"
			then
				succeeded_switch=y
			fi
			;;
		normal)
			if error_message="$(git switch --quiet "$current_branch" 2>&1 1>&3)"
			then
				succeeded_switch=y
			fi
			;;
		detached)
			if error_message="$(git switch --quiet --detach --quiet "$current_branch" 2>&1 1>&3)"
			then
				succeeded_switch=y
			fi
			;;
	esac
	exec 3>&-
	if [ "$succeeded_switch" = y ]
	then
		put_files_into_working_copy "$(git rev-parse "$working_dir_changes_sha~0")" "$(git rev-parse "$working_dir_changes_sha~1")" "$(git rev-parse "$working_dir_changes_sha~2")"
		is_really_pop="$(if [ -f "$(make_stash_data_file_path)" ] ; then printf 'y' ; else printf 'n' ; fi)"
		delete_data
		if [ "$is_really_pop" = n ]
		then
			printf 'Successfully aborted '\''git istash apply'\''\n'
		else
			printf 'Successfully aborted '\''git istash pop'\''\n'
		fi 1>&2
	else
		{
			printf 'fatal: failed to restore HEAD to initial position\n'
			printf '%s\n' "$error_message"
			print_broken_operation_hint '--abort'
		} 1>&2
		return 1
	fi
}

do_quit() { # args...
	check_args_for_apply 0 "$@"
	check_data_files n y
	
	if [ "$is_pop" = n ]
	then
		exec sh "$lib_dir/git-istash-pop" --quit "$@"
	fi
	
	git rebase --quit 2>/dev/null || true  # Errors are ignored because if rebase is not in progress or broken, we still want to remove the data files.
	is_really_pop="$(if [ -f "$(make_stash_data_file_path)" ] ; then printf 'y' ; else printf 'n' ; fi)"
	delete_data
	
	if [ "$is_really_pop" = n ]
	then
		printf 'Successfully quit '\''git istash apply'\''\n'
	else
		printf 'Successfully quit '\''git istash pop'\''\n'
	fi 1>&2
}

do_apply() { # args...
	if [ "$continue_set" = y ]
	then
		do_continue "$@"
	elif [ "$abort_set" = y ]
	then
		do_abort "$@"
	elif [ "$quit_set" = y ]
	then
		do_quit "$@"
	else
		do_start "$@"
	fi
}

getopt_short_options='chq'
getopt_long_options='abort,_called-from-pop,_called-from-pop_,continue,quit'
getopt_result="$(getopt -o"$getopt_short_options" --long="$getopt_long_options" -n'error' -ssh -- "$@")"
eval set -- "$getopt_result"
abort_set=n
is_pop=n
continue_set=n
quit_set=n
while true
do
	case "$1" in
	--abort)
		abort_set=y
		;;
	--_called-from-pop*)
		is_pop=y
		;;
	-c|--continue)
		continue_set=y
		;;
	-h)
		print_help
		exit 0
		;;
	-q|--quit)
		quit_set=y
		;;
	--)
		shift
		break
		;;
	esac
	shift
done
if [ $continue_set = y ] && [ $abort_set = y ] && [ $quit_set = y ]
then
	printf 'error: you can choose continue, abort or quit at your discretion but the rule is that you can only have one\n' 1>&2
	exit 1
fi
if [ $abort_set = y ] && [ $quit_set = y ]
then
	printf 'error: either abort or quit; there is no middle road\n' 1>&2
	exit 1
fi
if [ $continue_set = y ] && [ $abort_set = y ]
then
	printf 'error: unclear whether to continue aborting or to abort continuing\n' 1>&2
	exit 1
fi
if [ $continue_set = y ] && [ $quit_set = y ]
then
	printf 'error: unclear whether to continue quitting or to quit continuing\n' 1>&2
	exit 1
fi

lib_dir="$(cd "$(dirname "$0")" ; pwd)"
cd "$(git rev-parse --show-toplevel)"
target_data_file="$(make_target_data_file_path)"
working_dir_sha_file="$(make_working_dir_sha_file_path)"
do_apply "$@"
