#!/usr/bin/env sh

set -eu

. "$(dirname "$0")/git-istash-commons"
. "$(dirname "$0")/git-istash-io"

print_help() {
	printf 'git istash pop - Improved version of "git stash pop" that can handle conflicts\n    without loosing information about the files in index.\n'
	printf '\n'
	printf 'This is only a rudimentary help text. Prefer "git help istash" if available.\n'
	printf '\n'
	printf 'Usage: git istash pop [<option>...] [<stash>]\n'
	printf '   or: git istash pop (-c | --continue | --abort | --quit)\n'
	printf '   or: git istash pop -h\n'
	printf '\n'
	printf 'Options:\n'
	printf '\t--abort\t\t- Abort the previous operation and return the repository\n\t\t\t  to the state before it started.\n'
	printf '\t--color[=<when>] - Allow use of ANSI color codes.\n\t\t\t  <when> can be one of always, never, or auto.\n\t\t\t  Omitting the argument is equivalent to always.\n'
	printf '\t--no-color\t- Same as --color=never.\n'
	printf '    -c, --continue\t- Resume the previous operation.\n\t\t\t  (Conflicts need to be resolved before that.)\n'
	printf '    -h\t\t\t- Print this help text and exit.\n'
	printf '    -q, --quiet\t\t- Suppress human-readable summaries and information.\n'
	printf '\t--quit\t\t- Abort the operation but don'\''t restore the repository\n\t\t\t  state nor move the HEAD.\n'
	printf '\t--summary=<mode> - Set summary to "complete" / "non-ignored" / "off".\n'
}

set +e
check_for_option_h_in_command 'git-istash-apply' "$@"
result=$?
set -e
if [ $result -eq 0 ]
then
	print_help
	exit 0
fi

exec sh "$(dirname "$0")/git-istash-apply" --_called-from-pop_ "$@"
