#!/usr/bin/env sh

set -eu

. "$(dirname "$0")/git-istash-commons"
. "$(dirname "$0")/git-istash-io"
. "$(dirname "$0")/git-istash-vanilla-format"

print_help() {
	printf 'git istash apply - Improved version of "git stash apply" that can handle\n    conflicts without loosing information about the files in index.\n'
	printf '\n'
	printf 'This is only a rudimentary help text. Prefer "git help istash" if available.\n'
	printf '\n'
	printf 'Usage: git istash apply [<option>...] [<stash>]\n'
	printf '   or: git istash apply (-c | --continue | --abort | --quit)\n'
	printf '   or: git istash apply -h\n'
	printf '\n'
	printf 'Options:\n'
	printf '\t--abort\t\t- Abort the previous operation and return the repository\n\t\t\t  to the state before it started.\n'
	printf '\t--color[=<when>] - Allow use of ANSI color codes.\n\t\t\t  <when> can be one of always, never, or auto.\n\t\t\t  Omitting the argument is equivalent to always.\n'
	printf '\t--no-color\t- Same as --color=never.\n'
	printf '    -c, --continue\t- Resume the previous operation.\n\t\t\t  (Conflicts need to be resolved before that.)\n'
	printf '    -h\t\t\t- Print this help text and exit.\n'
	printf '    -q, --quiet\t\t- Suppress human-readable summaries and information.\n'
	printf '\t--quit\t\t- Abort the operation but don'\''t restore the repository\n\t\t\t  state nor move the HEAD.\n'
	printf '\t--summary=<mode> - Set summary to "complete" / "non-ignored" / "off".\n'
}

save_data() {
	if [ "$curr_branch_type" = 'orphan' ]
	then
		printf '~%s\n' "$current_branch" >"$target_data_file"
	else
		printf '%s\n' "$current_branch" >"$target_data_file"
	fi
	
	printf '%s\n' "$working_dir_changes_sha" >"$working_dir_sha_file"
	
	if [ "$sub_command_name" = 'pop' ]
	then
		printf '%s\n' "$stash" >"$stash_data_file"
	fi
}
load_target_data() {
	if [ "$(wc -l <"$target_data_file")" -ne 1 ]
	then
		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$sub_command_name"
		printf_fatal \''%s'\'' doesn'\''t have exactly 1 line\n' "$target_data_file"
		broken_operation_hint "$sub_command_name"
		fatal
	fi
	current_branch="$(cat "$target_data_file")"
	if [ "${current_branch#[~]}" != "$current_branch" ]
	then
		current_branch="${current_branch#[~]}"
		curr_branch_type='orphan'
	else
		curr_branch_type='normal'
	fi
	if ! git rev-parse --quiet --verify "$current_branch^{commit}" 1>/dev/null
	then
		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$sub_command_name"
		printf_fatal \''%s'\'' contains an invalid commit hash\n' "$target_data_file"
		broken_operation_hint "$sub_command_name"
		fatal
	fi
	if [ "$curr_branch_type" != 'orphan' ] && [ "$(git rev-parse "$current_branch")" = "$current_branch" ]
	then
		curr_branch_type='detached'
	fi
}
load_working_dir_data() {
	if [ "$(wc -l <"$working_dir_sha_file")" -ne 1 ]
	then
		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$sub_command_name"
		printf_fatal \''%s'\'' doesn'\''t have exactly 1 line\n' "$working_dir_sha_file"
		broken_operation_hint "$sub_command_name"
		fatal
	fi
	working_dir_changes_sha="$(cat "$working_dir_sha_file")"
	if ! git rev-parse --quiet --verify "$working_dir_changes_sha^{commit}" 1>/dev/null
	then
		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$sub_command_name"
		printf_fatal \''%s'\'' contains an invalid commit hash\n' "$working_dir_sha_file"
		broken_operation_hint "$sub_command_name"
		fatal
	fi
}
load_stash_data() {
	if [ "$(wc -l <"$stash_data_file")" -ne 1 ]
	then
		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$sub_command_name"
		printf_fatal \''%s'\'' doesn'\''t have exactly 1 line\n' "$stash_data_file"
		broken_operation_hint "$sub_command_name"
		fatal
	fi
	stash="$(cat "$stash_data_file")"
	if ! [ "$stash" -eq "$stash" ] 2>/dev/null || [ "$stash" -lt 0 ]
	then
		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$sub_command_name"
		printf_fatal \''%s'\'' doesn'\''t contain a positive integer\n' "$stash_data_file"
		broken_operation_hint "$sub_command_name"
		fatal
	fi
	if [ "$stash" -ge "$(git rev-list --walk-reflogs --count --ignore-missing refs/stash)" ]
	then
		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$sub_command_name"
		printf_fatal \''%s'\'' contains an invalid stash number\n' "$stash_data_file"
		broken_operation_hint "$sub_command_name"
		fatal
	fi
}
load_data() { # is_continue
	load_target_data
	load_working_dir_data
	if [ "$sub_command_name" = 'pop' ] && [ "$1" = y ]
	then
		load_stash_data
	fi
}
delete_data() {
	rm -f "$target_data_file"
	rm -f "$working_dir_sha_file"
	if [ "$sub_command_name" = 'pop' ]
	then
		rm -f "$stash_data_file"
	fi
}

check_args_for_apply() { # max_free_args args...
	check_args "istash $sub_command_name" "$@"
}

check_stash_for_pop() {
	if [ "$stash" -eq "$stash" ] 2>/dev/null
	then
		:
	else
		error 'can only pop '\''refs/stash'\'' or entries of its reflog\n'
	fi
}

put_files_into_working_copy() { # untracked_changes_sha non_staged_changes_sha staged_changes_sha
	git restore --quiet --source="$3" -- . 2>/dev/null || true
	git add -- .
	git restore --quiet --source="$1" -- . 2>/dev/null || true
	git --no-literal-pathspecs ls-tree -r --name-only "$2" -z :/ \
	| xargs -r0 -- git --literal-pathspecs add --intent-to-add --
}

print_changes_summary() {
	summary_mode="$(get_summary_mode)"
	if [ "$summary_mode" = 'off' ]
	then
		return
	fi
	if is_color_enabled_for_summary
	then
		header_color_escape_code="$(get_color_for_summary 'header')"
		updated_color_escape_code="$(get_color_for_summary 'updated')"
		changed_color_escape_code="$(get_color_for_summary 'changed')"
		untracked_color_escape_code="$(get_color_for_summary 'untracked')"
		reset_escape_code="$(get_color 'reset')"
	else
		header_color_escape_code=''
		updated_color_escape_code=''
		changed_color_escape_code=''
		untracked_color_escape_code=''
		reset_escape_code=''
	fi
	printf '\n%sChanges made to the working directory:%s\n' "$header_color_escape_code" "${header_color_escape_code:+$reset_escape_code}"
	zero_sha='0000000000000000000000000000000000000000'
	all_changes="$(
		set -eu
		{
			git diff --no-renames --name-only -z "$working_dir_changes_sha~2" "$staged_changes_sha"
			git diff --no-renames --name-only -z "$working_dir_changes_sha~1" "$non_staged_changes_sha"
			git diff --no-renames --name-only -z "$working_dir_changes_sha~0" "$untracked_changes_sha"
			if [ "$summary_mode" = 'complete' ]
			then
				git ls-files --no-cached --no-deleted --no-modified --others --no-ignored --no-stage --no-killed --exclude-standard -z
				git ls-files --no-cached --no-deleted --no-modified --others --ignored --no-stage --no-killed --exclude-standard -z
			fi
		} \
		| convert_to_octal_lines \
		| sort -u \
		| relax_octal_sanitization \
		| while read -r file
		do
			# The abbreviations used here:
			# the 1st letter is "old" / "new"
			# the 2nd letter is "index" / "tracked" / "untracked".
			#shellcheck disable=SC2015
			oi_sha="$(
				printf '%s:%b' "$working_dir_changes_sha~2" "$file" \
				| xargs -0 -- git --literal-pathspecs rev-parse --verify 2>/dev/null
			)" && oi=1 || { oi_sha="$zero_sha" ; oi=0 ; }
			printf '%s:%b' "$working_dir_changes_sha~1" "$file" \
			| xargs -0 -- git --literal-pathspecs rev-parse --verify 1>/dev/null 2>&1 \
			&& ot=1 || ot=0
			#shellcheck disable=SC2015
			ou_sha="$(
				printf '%s:%b' "$working_dir_changes_sha~0" "$file" \
				| xargs -0 -- git --literal-pathspecs rev-parse --verify 2>/dev/null
			)" && ou=1 || { ou_sha="$zero_sha" ; ou=0 ; }
			ni_sha="$(
				if ! printf '%b' "$file" \
					| xargs -0 -- git --literal-pathspecs status --porcelain -- \
					| grep -E -q '^.A'
				then
					printf '%b' "$file" \
					| xargs -0 -- git --literal-pathspecs ls-files -s -- \
					| cut -d' ' -f2
				else
					printf '%b' "$file" \
					| xargs -0 -- git --literal-pathspecs status --porcelain=2 -- \
					| head -n1 \
					| cut -d' ' -f8
				fi
			)" ; ni_sha="${ni_sha:-"$zero_sha"}" ; test "$ni_sha" != "$zero_sha" && ni=1 || ni=0
			#shellcheck disable=SC2015
			nt_sha="$(
				printf '%b' "$file" \
				| xargs -0 -- git --literal-pathspecs ls-files --error-unmatch -- 1>/dev/null 2>&1 \
				&& printf '%b' "$file" \
				| xargs -0 -- git --literal-pathspecs hash-object -- 2>/dev/null
			)" && nt=1 || { nt_sha="$zero_sha" ; nt=0 ; }
			#shellcheck disable=SC2015
			nu_sha="$(
				printf '%b' "$file" \
				| xargs -0 -- git --literal-pathspecs hash-object -- 2>/dev/null
			)" && nu=1 || nu=0
			# The ifs can be interpreted by their direct meaning but it's complicated.
			# The case statements are in a large part generated by a Karnaugh map solver. You can find the input data and the result in the commit message of 50abf565859942c5e19dc2dbea8dd583ddd4bf76.
			# index
			case "$oi-$ni" in
			0-1)
				printf 'i A %s\n' "$file"
				;;
			1-0)
				printf 'i D %s\n' "$file"
				;;
			1-1)
				if [ "$ni_sha" != "$oi_sha" ]
				then
					printf 'i M %s\n' "$file"
				fi
				;;
			esac
			# tracked
			case "$oi$ot-$ni$nt" in
			1?-01|?0-01|10-?1)
				printf 't A %s\n' "$file"
				;;
			0?-10|?1-10|01-?0)
				printf 't D %s\n' "$file"
				;;
			0?-11|?1-11|01-?1)
				if [ "$ni_sha" = "$oi_sha" ] || [ "$nt_sha" != "$ni_sha" ]
				then
					old_changes="$(
						printf '%b' "$file" \
						| xargs -0 -- git --literal-pathspecs diff-files -p -- \
						| sed -E -e 's/^@@.*$/@@/'
					)"
					new_changes="$(
						printf '%b' "$file" \
						| xargs -0 -- git --literal-pathspecs diff-tree -p "$working_dir_changes_sha~2" "$working_dir_changes_sha~1" -- \
						| sed -E -e 's/^@@.*$/@@/'
					)"
					if [ "$old_changes" != "$new_changes" ]
					then
						printf 't M %s\n' "$file"
					fi
				fi
				;;
			esac
			# untracked
			if ! printf '%b' "$file" \
				| xargs -0 -- git check-ignore --quiet --
			then
				#shellcheck disable=SC2221,SC2222
				case "$oi$ot$ou-$ni$nt$nu" in
				?1?-?01|??0-?01)
					printf 'u C %s\n' "$file"
					;;
				?01-0?0)
					printf 'u D %s\n' "$file"
					;;
				11?-?01|?01-?01)
					if [ "$nu_sha" != "$ou_sha" ]
					then
						printf 'u M %s\n' "$file"
					fi
					;;
				esac
			elif [ "$summary_mode" = 'complete' ]
			then
				if [ "$ou" = '1' ]
				then
					printf 'u I %s\n' "$file"
				elif [ "$nu" = 1 ]
				then
					if printf '%s:%b' "$untracked_changes_sha" "$file" \
						| xargs -0 -- git --literal-pathspecs rev-parse --verify --quiet 1>/dev/null 2>&1
					then
						printf 'u T %s\n' "$file"
					fi
				fi
			fi
		done
	)"
	if [ -n "$all_changes" ]
	then
		index_changes="$(
			printf '%s' "$all_changes" \
			| sed -En 's/^i (.*)$/\1/p'
		)"
		tracked_changes="$(
			printf '%s' "$all_changes" \
			| sed -En 's/^t (.*)$/\1/p'
		)"
		untracked_changes="$(
			printf '%s' "$all_changes" \
			| sed -En 's/^u (.*)$/\1/p'
		)"
		{
			if [ -n "$index_changes" ]
			then
				printf '    %sindex:%s\\n' "$header_color_escape_code" "${header_color_escape_code:+$reset_escape_code}"
				printf '%s\n' "$index_changes" \
				| sed -E -e 's/^A (.+)$/added:'"$tab$tab"'\1/' \
					-e 's/^M (.+)$/modified:'"$tab"'\1/' \
					-e 's/^D (.+)$/deleted:'"$tab"'\1/' \
					-e 's/^.+$/\t'"$updated_color_escape_code"'&'"${updated_color_escape_code:+$reset_escape_code}"'\\n/'
			fi
			if [ -n "$tracked_changes" ]
			then
				printf '    %stracked files:%s\\n' "$header_color_escape_code" "${header_color_escape_code:+$reset_escape_code}"
				printf '%s\n' "$tracked_changes" \
				| sed -E -e 's/^A (.+)$/added:'"$tab$tab"'\1/' \
					-e 's/^M (.+)$/modified:'"$tab"'\1/' \
					-e 's/^D (.+)$/deleted:'"$tab"'\1/' \
					-e 's/^.+$/\t'"$changed_color_escape_code"'&'"${changed_color_escape_code:+$reset_escape_code}"'\\n/'
			fi
			if [ -n "$untracked_changes" ]
			then
				printf '    %suntracked files:%s\\n' "$header_color_escape_code" "${header_color_escape_code:+$reset_escape_code}"
				printf '%s\n' "$untracked_changes" \
				| sed -E -e 's/^C (.+)$/created:'"$tab"'\1/' \
					-e 's/^M (.+)$/modified:'"$tab"'\1/' \
					-e 's/^D (.+)$/deleted:'"$tab"'\1/' \
					-e 's/^T (.+)$/touched:'"$tab"'\1/' \
					-e 's/^I (.+)$/ignored:'"$tab"'\1/' \
					-e 's/^.+$/\t'"$untracked_color_escape_code"'&'"${untracked_color_escape_code:+$reset_escape_code}"'\\n/'
			fi
		} \
		| tr '\n' '\0' \
		| xargs -0 -- printf '%b'
	else
		printf '\t%sno changes were made%s\n' "$header_color_escape_code" "${header_color_escape_code:+$reset_escape_code}"
	fi
}

print_rebase_problem() {
	if ! current_rebase_step="$(cat "$(git rev-parse --git-path 'rebase-merge')/msgnum")" \
		|| ! [ "$current_rebase_step" -eq "$current_rebase_step" ] 2>/dev/null \
		|| [ "$current_rebase_step" -lt 2 ] || [ "$current_rebase_step" -gt 6 ]
	then
		printf 'Cannot determine the current stage of merging the stash into the working directory!\n'
	else
		printf 'Currently merging '
		case "$current_rebase_step" in
			2) printf 'staged changes' ;;
			3|4) printf 'unstaged changes' ;;
			5|6) printf 'untracked changes' ;;
		esac
		printf ' from '
		case "$current_rebase_step" in
			2|4|6) printf 'stash' ;;
			3|5) printf 'working directory' ;;
		esac
		printf ' into '
		case "$current_rebase_step" in
			2|4|6) ;;
			3|5) printf 'already merged ' ;;
		esac
		case "$current_rebase_step" in
			2|3|4) printf 'staged changes' ;;
			5|6) printf 'tracked changes' ;;
		esac
		case "$current_rebase_step" in
			2|3|5) ;;
			4|6) printf ' already merged with ' ;;
		esac
		case "$current_rebase_step" in
			2|3|5) ;;
			4) printf 'unstaged changes' ;;
			6) printf 'untracked changes' ;;
		esac
		case "$current_rebase_step" in
			2|4|6) printf ' from working directory' ;;
			3|5) ;;
		esac
		printf '.\n'
	fi 1>&2
	hint 'Conflicts' 'use '\''git istash --continue'\'' after fixing the conflicts\nor, to undo everything '\''git istash %s'\'' did, run '\''git istash --abort'\''\n' "$sub_command_name"
}

end_with_rebase_problem() {
	if [ "$is_quiet" = n ]
	then
		print_rebase_problem
	fi
	return 2
}
end_with_success() {
	if { [ "$curr_branch_type" != 'orphan' ] && [ "$(git rev-parse HEAD~6)" != "$(git rev-parse "$current_branch")" ] ; } \
		|| { [ "$curr_branch_type" = 'orphan' ] && [ "$(git rev-list --no-walk --count HEAD~6^@)" != '0' ] ; }
	then
		fatal 'HEAD is not in the correct position after rebasing\n'
	fi
	untracked_changes_sha="$(git rev-parse HEAD~0)"
	non_staged_changes_sha="$(git rev-parse HEAD~2)"
	staged_changes_sha="$(git rev-parse HEAD~4)"
	case "$curr_branch_type" in
		orphan)
			if [ -n "$(git ls-tree -r --name-only HEAD~6)" ]
			then
				# This error is untested because it's hard to come up with a scenario so contrived that it would occur.
				fatal 'the empty commit created for the command is not empty\n'
			fi
			git branch --quiet --delete --force "$current_branch"
			git switch --quiet --orphan "$current_branch"
			;;
		normal)
			git switch --quiet "$current_branch"
			;;
		detached)
			git switch --quiet --detach HEAD~6
			;;
	esac
	put_files_into_working_copy "$untracked_changes_sha" "$non_staged_changes_sha" "$staged_changes_sha"
	delete_data
	if [ "$is_quiet" != y ]
	then
		printf 'Stash of the old working dir: %s\n' "$(prepare_stash_of_working_dir)"
	fi
	if [ "$sub_command_name" = 'pop' ]
	then
		if [ "$is_quiet" != y ]
		then
			printf '\n'
			git stash drop "$stash"
		else
			git stash drop --quiet "$stash"
		fi
	fi
	if [ "$is_quiet" != y ]
	then
		print_changes_summary
		printf '\nSuccessfully %sed the stash\n' "$(printf '%s' "$sub_command_name" | sed -E 's/y$/i/;s/p$/&p/')"
	fi
}

check_data_files() { # continue abort quit
	operation_in_progress="$(find_data_files)"
	case "$operation_in_progress" in
		apply|pop)
			if [ "$operation_in_progress" = "$sub_command_name" ]
			then
				if [ "$1$2$3" != 'nnn' ]
				then
					return 0
				fi
			elif [ "$sub_command_name" = 'apply' ]
			then
				if [ "$3" != 'n' ]
				then
					sub_command_name="$operation_in_progress"
					return 0
				fi
			else
				if [ "$2$3" != 'nn' ]
				then
					sub_command_name="$operation_in_progress"
					return 0
				fi
			fi
			print_error_for_data_files_check "$operation_in_progress" "$sub_command_name"
			error
			;;
		error-*)
			if [ "$3" != 'n' ]
			then
				sub_command_name="${operation_in_progress#error-}"
				return 0
			fi
			print_error_for_data_files_check "$operation_in_progress" "$sub_command_name"
			error
			;;
		nothing)
			if [ "$1$2$3" = 'nnn' ]
			then
				return 0
			fi
			error 'no istash %s in progress\n' "$sub_command_name"
			;;
	esac
}

prepare_current_branch() {
	if [ "$curr_branch_type" = 'orphan' ]
	then
		git commit --quiet --only --allow-empty --message 'Temporary commit by "git-stash"'
	fi
}

commit_working_directory() {
	# initialization
	default_message="$(git rev-list --no-commit-header --format='%h %s' --max-count=1 HEAD)"
	message="Working directory changes prior to applying stash $(git rev-parse "$(get_stash_commit "$stash")")"
	if [ "$curr_branch_type" != 'detached' ]
	then
		branch_name_for_msg="$(git branch --show-current)"
	else
		branch_name_for_msg='(no branch)'
	fi
	git switch --quiet --detach HEAD
	
	# staged
	git commit --quiet --message="index on $branch_name_for_msg: $default_message" --allow-empty
	
	# unstaged
	git --no-literal-pathspecs add --update :/ 1>&2 2>/dev/null || true
	git commit --quiet --message="On $branch_name_for_msg: $message" --allow-empty
	
	# untracked
	git --no-literal-pathspecs add --all --intent-to-add :/ 2>/dev/null || true
	git --no-literal-pathspecs add --update :/ 1>&2 2>/dev/null || true
	git commit --quiet --message="untracked files on $branch_name_for_msg: $default_message" --allow-empty
	
	# save sha
	working_dir_changes_sha="$(git rev-parse 'HEAD')"
}

prepare_stash_of_working_dir() {
	if [ "$(git rev-parse "$working_dir_changes_sha^{tree}")" = "$(git rev-parse "$working_dir_changes_sha~1^{tree}")" ]
	then
		tangle_stash "$working_dir_changes_sha~1" n
	else
		tangle_stash "$working_dir_changes_sha" y
	fi
}

run_first_time_rebase() { # untangled_stash_sha
	#shellcheck disable=SC2031
	todo_list_editor="sh -c \"
		x=\\\"\\\$(cat \\\"\\\$1\\\")\\\"
		printf '%s\\\\n' \\\"\\\$x\\\" \\\\
		| sed -E \\\\
			-e '1i\\\\${nl}pick $working_dir_changes_sha~2 Staged working directory' \\\\
			-e '2i\\\\${nl}pick $working_dir_changes_sha~1 Unstaged working directory' \\\\
			-e '3i\\\\${nl}pick $working_dir_changes_sha~0 Untracked working directory' \\\\
		>\\\"\\\$1\\\"
		\" _"
	set -- --onto "$current_branch" "$1~3" "$1" --empty=keep --keep-empty --reapply-cherry-picks --interactive
	if [ "$is_quiet" = n ]
	then
		GIT_SEQUENCE_EDITOR="$todo_list_editor" git rebase "$@" 2>/dev/null
	else
		GIT_SEQUENCE_EDITOR="$todo_list_editor" git rebase "$@" 1>/dev/null 2>&1
	fi
}

start_rebase() { # untangled_stash_sha
	if run_first_time_rebase "$1"
	then
		end_with_success
	elif are_there_conflicts
	then
		end_with_rebase_problem
	else
		do_abort
		fatal
	fi
}

do_start() { # args...
	check_args_for_apply 1 "$@"
	check_data_files n n n
	check_other_git_commands_state
	find_stash "$@"
	if [ "$sub_command_name" = 'pop' ]
	then
		check_stash_for_pop
	fi
	find_current_branch
	prepare_current_branch
	commit_working_directory
	save_data
	stash_sha="$(get_stash_commit "$stash")"
	untangled_stash_sha="$(untangle_git_stash "$stash_sha")"
	start_rebase "$untangled_stash_sha"
}

run_continued_rebase() {
	if [ "$is_quiet" = n ]
	then
		git -c 'core.editor=true' rebase --continue
	else
		git -c 'core.editor=true' rebase --continue 1>/dev/null
	fi
}

do_continue() { # args...
	check_args_for_apply 0 "$@"
	check_data_files y n n
	load_data y
	
	git commit --quiet --allow-empty --no-edit 1>/dev/null 2>&1 || true
	exec 3>&1
	if stderr="$(run_continued_rebase 2>&1 1>&3)"
	then
		exec 3>&-
		end_with_success
	elif are_there_conflicts
	then
		exec 3>&-
		end_with_rebase_problem
	else
		exec 3>&-
		git reset --quiet --soft HEAD~
		printf '%s' "$stderr" | color_fatal 1>&2
		fatal
	fi
}

do_abort() { # args...
	check_args_for_apply 0 "$@"
	check_data_files n y n
	load_data n
	
	error_message="$(git rebase --abort 2>&1 || true)"  # Errors are ignored because if rebase is not in progress, we still want to try to restore HEAD.
	if [ -n "$error_message" ]
	then
		printf '%s\n' "$error_message" | color_fatal 1>&2
	fi
	git reset --quiet --hard
	succeeded_switch=n
	exec 3>&1
	case "$curr_branch_type" in
		orphan)
			git branch --quiet --delete --force "$current_branch"
			if error_message="$(git switch --quiet --orphan "$current_branch" 2>&1 1>&3)"
			then
				succeeded_switch=y
			fi
			;;
		normal)
			if error_message="$(git switch --quiet "$current_branch" 2>&1 1>&3)"
			then
				succeeded_switch=y
			fi
			;;
		detached)
			if error_message="$(git switch --quiet --detach --quiet "$current_branch" 2>&1 1>&3)"
			then
				succeeded_switch=y
			fi
			;;
	esac
	exec 3>&-
	
	if [ "$succeeded_switch" = y ]
	then
		put_files_into_working_copy \
			"$(git rev-parse "$working_dir_changes_sha~0")" \
			"$(git rev-parse "$working_dir_changes_sha~1")" \
			"$(git rev-parse "$working_dir_changes_sha~2")"
		
		delete_data
		
		if [ "$is_quiet" = n ]
		then
			printf 'Successfully aborted '\''git istash %s'\''\n' "$sub_command_name" 1>&2
		fi
	else
		printf_fatal 'failed to restore HEAD to initial position\n'
		printf '%s\n' "$error_message" | color_fatal 1>&2
		broken_operation_hint '--abort'
		fatal
	fi
}

do_quit() { # args...
	check_args_for_apply 0 "$@"
	check_data_files n n y
	
	git rebase --quit 2>/dev/null || true  # Errors are ignored because if rebase is not in progress or broken, we still want to remove the data files.
	delete_data
	
	if [ "$is_quiet" = n ]
	then
		printf 'Successfully quit '\''git istash %s'\''\n' "$sub_command_name" 1>&2
	fi
}

do_apply() { # args...
	if [ "$continue_set" = y ]
	then
		do_continue "$@"
	elif [ "$abort_set" = y ]
	then
		do_abort "$@"
	elif [ "$quit_set" = y ]
	then
		do_quit "$@"
	else
		do_start "$@"
	fi
}

getopt_short_options='chq'
getopt_long_options='abort,_called-from-pop,_called-from-pop_,color::,no-color,continue,quiet,quit,summary:'
normalized_options="$(get_options_color "$getopt_short_options" "$getopt_long_options" "$@")"
eval set -- "$normalized_options"
abort_set=n
sub_command_name='apply'
continue_set=n
is_quiet=n
quit_set=n
while true
do
	case "$1" in
	--abort)
		abort_set=y
		;;
	--_called-from-pop*)
		sub_command_name='pop'
		;;
	--color)
		shift
		set_color_for_all "$1"
		;;
	--no-color)
		set_color_for_all 'never'
		;;
	-c|--continue)
		continue_set=y
		;;
	-h)
		print_help
		exit 0
		;;
	-q|--quiet)
		is_quiet=y
		;;
	--quit)
		quit_set=y
		;;
	--summary)
		shift
		set_summary_mode "$1"
		;;
	--)
		shift
		break
		;;
	esac
	shift
done
if [ $continue_set = y ] && [ $abort_set = y ] && [ $quit_set = y ]
then
	printf_error 'you can choose continue, abort or quit at your discretion but the rule is that you can only have one\n'
	help_hint "istash $sub_command_name"
	error
fi
if [ $abort_set = y ] && [ $quit_set = y ]
then
	printf_error 'either abort or quit; there is no middle road\n'
	help_hint "istash $sub_command_name"
	error
fi
if [ $continue_set = y ] && [ $abort_set = y ]
then
	printf_error 'unclear whether to continue aborting or to abort continuing\n'
	help_hint "istash $sub_command_name"
	error
fi
if [ $continue_set = y ] && [ $quit_set = y ]
then
	printf_error 'unclear whether to continue quitting or to quit continuing\n'
	help_hint "istash $sub_command_name"
	error
fi

cd "$(git rev-parse --show-toplevel)"
target_data_file="$(make_target_data_file_path)"
working_dir_sha_file="$(make_working_dir_sha_file_path)"
stash_data_file="$(make_stash_data_file_path)"
do_apply "$@"
