#!/usr/bin/env sh

set -eu

. "$(dirname "$0")/git-istash-commons"

print_help() {
	printf 'git istash pop - Improved version of "git stash pop" that can handle conflicts\n    without loosing information about the files in index.\n'
	printf '\n'
	printf 'This is only a rudimentary help text. Prefer "git help istash" if available.\n'
	printf '\n'
	printf 'Usage: git istash pop [<option>...] [<stash>]\n'
	printf '   or: git istash pop (-c | --continue | --abort | --quit)\n'
	printf '   or: git istash pop -h\n'
	printf '\n'
	printf 'Options:\n'
	printf '\t--abort\t\t- Abort the previous operation and return the repository\n\t\t\t  to the state before it started.\n'
	printf '    -c, --continue\t- Resume the previous operation.\n\t\t\t  (Conflicts need to be resolved before that.)\n'
	printf '    -h\t\t\t- Show this help text and exit.\n'
	printf '\t--quit\t\t- Abort the operation but don'\''t restore the repository\n\t\t\t  state nor move the HEAD.\n'
}

save_data() {
	printf '%s\n' "$stash" >"$stash_data_file"
}
load_stash_data() { # subcommand
	if [ "$(wc -l <"$stash_data_file")" -ne 1 ]
	then
		printf 'fatal: '\''git istash pop'\'' seems to be running but the data files are broken\n' 1>&2
		printf 'fatal: '\''%s'\'' doesn'\''t have exactly 1 line\n' "$stash_data_file" 1>&2
		print_quit_hint "$1"
		return 1
	fi
	stash="$(cat "$stash_data_file")"
	if ! [ "$stash" -eq "$stash" ] 2>/dev/null || [ "$stash" -lt 0 ]
	then
		printf 'fatal: '\''git istash pop'\'' seems to be running but the data files are broken\n' 1>&2
		printf 'fatal: '\''%s'\'' doesn'\''t contain a positive integer\n' "$stash_data_file" 1>&2
		print_quit_hint "$1"
		return 1
	fi
	if [ "$stash" -ge "$(git rev-list --walk-reflogs --count --ignore-missing refs/stash)" ]
	then
		printf 'fatal: '\''git istash pop'\'' seems to be running but the data files are broken\n' 1>&2
		printf 'fatal: '\''%s'\'' contains an invalid stash number\n' "$stash_data_file" 1>&2
		print_quit_hint "$1"
		return 1
	fi
}
load_data() { # subcommand
	load_stash_data "$1"
}
delete_data() {
	rm -f "$stash_data_file"
}

check_args_for_pop() { # max_free_args args...
	check_args 'istash pop' "$@"
}

end_with_success() {
	delete_data
	git stash drop "$stash"
	printf '\nSuccessfully popped the stash\n'
}

check_stash_for_pop() {
	if [ "$stash" -eq "$stash" ] 2>/dev/null
	then
		:
	else
		printf 'error: can only pop '\''refs/stash'\'' or entries of its reflog\n' 1>&2
		return 1
	fi
}

print_quit_hint() { # subcommand
	printf_color 2 '\033[33m'
	if [ "$1" = 'pop' ]
	then
		printf 'hint: fix the problem and finalize that operation before starting a new one\n'
	else
		printf 'hint: fix the problem and finalize that operation before starting '\''istash pop'\''\n'
	fi
	printf 'hint: or run '\''git istash --quit'\'' to forcefully cancel it\n'
	printf_color 2 '\033[39m'
} 1>&2

check_data_files() { # resume abort quit
	operation_in_progress="$(find_data_files)"
	case "$operation_in_progress" in
		pop)
			if [ "$1" = y ] || [ "$2" = y ] || [ "$3" = y ] ; then return 0 ; fi
			{
				printf_color 2 '\033[33m'
				printf 'error: '\''git istash %s'\'' is already in progress\n' "$operation_in_progress"
				printf 'hint: use '\''git istash --continue'\'' or '\''git istash --abort'\''\n'
				printf_color 2 '\033[39m'
			} 1>&2
			return 1
			;;
		apply)
			if [ "$2" = y ] || [ "$3" = y ] ; then return 0 ; fi
			{
				printf_color 2 '\033[33m'
				printf 'error: there is currently '\''git istash %s'\'' in progress\n' "$operation_in_progress"
				printf_color 2 '\033[39m'
			} 1>&2
			return 1
			;;
		error-*)
			if [ "$3" = y ] ; then return 0 ; fi
			{
				operation_in_progress="$(printf '%s' "$operation_in_progress" | tail -c +7)"
				printf_color 2 '\033[31m'
				if [ -f "$(make_target_data_file_path)" ]
				then
					printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$operation_in_progress" 1>&2
					printf 'fatal: '\''%s'\'' is missing\n' "$(make_working_dir_sha_file_path)"
				elif [ -f "$(make_working_dir_sha_file_path)" ]
				then
					printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$operation_in_progress" 1>&2
					printf 'fatal: '\''%s'\'' is missing\n' "$(make_target_data_file_path)"
				else
					printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$operation_in_progress" 1>&2
					printf 'fatal: '\''%s'\'' and '\''%s'\'' are missing!' "$(make_target_data_file_path)" "$(make_working_dir_sha_file_path)"
				fi
				printf_color 2 '\033[33m'
				printf_color 2 '\033[39m'
			} 1>&2
			print_quit_hint "$operation_in_progress"
			return 1
			;;
		nothing)
			if [ "$1" = n ] && [ "$2" = n ] && [ "$3" = n ] ; then return 0 ; fi
			printf 'error: no istash pop in progress\n' 1>&2
			return 1
			;;
	esac
}

run_apply() { # args...
	sh "$lib_dir/git-istash-apply" --_called-from-pop_ "$@"
}

do_start() { # args...
	check_args_for_pop 1 "$@"
	check_data_files n n n
	check_other_git_commands_state
	find_stash "$@"
	check_stash_for_pop
	save_data
	if run_apply -- "$@"
	then
		end_with_success
	elif [ $? -eq 2 ]
	then
		return 2
	else
		delete_data
		return 1
	fi
}

do_continue() { # args...
	check_args_for_pop 0 "$@"
	check_data_files y n n
	load_data 'pop'
	run_apply --continue
	end_with_success
}

do_abort() { # args...
	check_args_for_pop 0 "$@"
	check_data_files n y n
	run_apply --abort
	delete_data
}

do_quit() { # args...
	check_args_for_pop 0 "$@"
	check_data_files n n y
	run_apply --quit
	delete_data
}

do_pop() { # args...
	if [ "$continue_set" = y ]
	then
		do_continue "$@"
	elif [ "$abort_set" = y ]
	then
		do_abort "$@"
	elif [ "$quit_set" = y ]
	then
		do_quit "$@"
	else
		do_start "$@"
	fi
}

getopt_short_options='chq'
getopt_long_options='abort,continue,quit'
getopt_result="$(getopt -o"$getopt_short_options" --long="$getopt_long_options" -n'error' -ssh -- "$@")"
eval set -- "$getopt_result"
abort_set=n
continue_set=n
quit_set=n
while true
do
	case "$1" in
	--abort)
		abort_set=y
		;;
	-c|--continue)
		continue_set=y
		;;
	-h)
		print_help
		exit 0
		;;
	-q|--quit)
		quit_set=y
		;;
	--)
		shift
		break
		;;
	esac
	shift
done
if [ $continue_set = y ] && [ $abort_set = y ] && [ $quit_set = y ]
then
	printf 'error: you can choose continue, abort or quit at your discretion but the rule is that you can only have one\n' 1>&2
	exit 1
fi
if [ $abort_set = y ] && [ $quit_set = y ]
then
	printf 'error: either abort or quit; there is no middle road\n' 1>&2
	exit 1
fi
if [ $continue_set = y ] && [ $abort_set = y ]
then
	printf 'error: unclear whether to continue aborting or to abort continuing\n' 1>&2
	exit 1
fi
if [ $continue_set = y ] && [ $quit_set = y ]
then
	printf 'error: unclear whether to continue quitting or to quit continuing\n' 1>&2
	exit 1
fi

lib_dir="$(cd "$(dirname "$0")" ; pwd)"
cd "$(git rev-parse --show-toplevel)"
stash_data_file="$(make_stash_data_file_path)"
do_pop "$@"
