#!/usr/bin/env sh

set -eu

. "$(dirname "$0")/git-istash-commons"
. "$(dirname "$0")/git-istash-io"

print_help() {
	printf 'git istash snatch - A version of "git istash create" that removes the stashed\n    changes from the working directory.\n'
	printf '\n'
	printf 'This is only a rudimentary help text. Prefer "git help istash" if available.\n'
	printf '\n'
	printf 'Usage: git istash snatch [<option>...]\n'
	printf '   or: git istash snatch -h\n'
	printf '\n'
	printf 'Options:\n'
	printf '    -a, --all\t\t- Stash and clean also untracked and ignored files.\n'
	printf '\t--allow-empty\t- Create a stash even if there are no suitable changes.\n'
	printf '\t--color[=<when>] - Allow use of ANSI color codes.\n\t\t\t  <when> can be one of always, never, or auto.\n\t\t\t  Omitting the argument is equivalent to always.\n'
	printf '\t--no-color\t- Same as --color=never.\n'
	printf '    -h\t\t\t- Print this help text and exit.\n'
	printf '    -k, --keep-index\t- Left intact all changes already added to the index.\n'
	printf '\t--no-keep-index\t- Cancel --keep-index.\n'
	printf '    -l, --leave-staged\t- Left intact all changes already added to the index\n\t\t\t  and don'\''t add them to stash.\n'
	printf '    -m, --message=MSG\t- Set stash description.\n'
	printf '\t--patch\t\t- Interactively select non-staged chunks to stash.\n'
	printf '\t--pathspec-from-file=FILE - Read pathspec from the specified file.\n'
	printf '\t--pathspec-file-nul - Treat the pathspec file as NUL-separated.\n\t\t\t  (Only valid with --pathspec-from-file.)\n'
	printf '    -q, --quiet\t\t- Suppress human-readable summaries and information.\n'
	printf '    -S, --staged\t- Left intact all changes NOT already added to the index\n\t\t\t  and don'\''t add them to stash.\n'
	printf '    -u, --include-untracked - Stash and clean also untracked files.\n'
	printf '\t--no-include-untracked - Do not touch untracked files even with --all.\n'
}

set +e
check_for_option_h_in_command 'git-istash-make-stash' "$@"
result=$?
set -e
if [ $result -eq 0 ]
then
	print_help
	exit 0
fi

exec sh "$(dirname "$0")/git-istash-make-stash" 'snatch' --no-store --remove-stashed "$@"
